version: "3.3"
services: 

  address-store:
    container_name: address-store
    image: docker.io/paawak/address-store:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      druto-chithhi-app-network:
        ipv4_address: 172.28.169.11

  druto-chithhi-ui:
    container_name: druto-chithhi-ui
    image: docker.io/paawak/druto-chithhi-ui:1.0
    depends_on:
      - address-store
    ports:
      - "4200:80"
    networks:
    - druto-chithhi-app-network    

networks:
  druto-chithhi-app-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"
    ipam:
        driver: default
        config:
          - 
            subnet: 172.28.169.0/24

