--
-- Table structure for table news_bulltein
--

CREATE TABLE ARTICLE (
  ID BIGINT PRIMARY KEY NOT NULL,
  HEADLINE CLOB NOT NULL,
  URL CLOB NOT NULL,
  PUBLISHER_NAME VARCHAR(200) NOT NULL,
  CLASSIFIER CHAR(1) NOT NULL,
  PUBLISHER_URL VARCHAR(200) NOT NULL,
  PUBLISHED_TIME DATE NOT NULL
);

