server:
  port: 8080
  servlet:
    contextPath: /news-bulletin
  
logging:
  level:
    root: INFO
    com.paawak.amex.demo.news: DEBUG
    org.springframework.web: INFO

spring:
  flyway:
    locations: classpath:/sql
  datasource:
    url: jdbc:h2:mem:news_bulletin
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true    
      settings:
        webAllowOthers: true
        trace: false
    


