CREATE SEQUENCE SEQ_COUNTRY;
CREATE SEQUENCE SEQ_CITY;
CREATE SEQUENCE SEQ_STATE;

CREATE TABLE country (
  id SMALLINT NOT NULL DEFAULT NEXTVAL('SEQ_COUNTRY'),
  name VARCHAR(250) NOT NULL UNIQUE,
  shortname VARCHAR(15) UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY  (id)
);


CREATE TABLE state (
  id INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_STATE'),
  name VARCHAR(250) NOT NULL UNIQUE,
  shortname VARCHAR(15) NOT NULL UNIQUE,
  country SMALLINT NOT NULL REFERENCES country(id),
  PRIMARY KEY  (id)
);


CREATE TABLE city (
  id INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_CITY'),
  name VARCHAR(250) NOT NULL,
  shortname VARCHAR(15),
  state INTEGER NOT NULL REFERENCES state(id),
  PRIMARY KEY  (id),
  UNIQUE (name, state)
);


