FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/client-account-0.0.1-SNAPSHOT-standalone.jar /client-account/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/client-account/app.jar"]
