/*
 * java
 *
 * Created on April 1, 2004, 1:10 AM
 */

package view;

/**
 *
 * @author  paawak
 */

import javax.swing.*;
import java.util.*;

import controller.*;
import view.controller.*;
import model.*;
import model.database.*;
import utils.general.*;


public class ClientAccountView extends javax.swing.JPanel implements TableListDB {
    
    /** Creates new form ClientAccountView */
    public ClientAccountView() {
        clientAccountController = new ClientAccountController();
        initComponents();
        ReadPropertyFile readMainProps = new ReadPropertyFile("controller/props/CommonProps");
        readProps = new ReadPropertyFile("view/props/ClientAccountViewProps",new Locale(readMainProps.getVal("defaultLocaleLanguage"),readMainProps.getVal("defaultLocaleCountry")));
        setLabels();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpClientType = new javax.swing.ButtonGroup();
        lbClientID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbShortName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAccNum = new javax.swing.JTextField();
        txtContactFirstName = new javax.swing.JTextField();
        txtContactMiddleName = new javax.swing.JTextField();
        txtContactLastName = new javax.swing.JTextField();
        txtTelephone1 = new javax.swing.JTextField();
        txtTelephone2 = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        pnlAddTitle = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbFullName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtShortName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbDetailsOfContactPerson = new javax.swing.JLabel();
        rdBtOrganisation = new javax.swing.JRadioButton();
        rdBtIndividual = new javax.swing.JRadioButton();
        pnlModifyTitle = new javax.swing.JPanel();
        lbTitle1 = new javax.swing.JLabel();
        pnlAddButtons = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btDone = new javax.swing.JButton();
        pnlModifyButtons = new javax.swing.JPanel();
        btSaveChanges = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        pnlSearchMain = new javax.swing.JPanel();

        lbClientID.setText("Client ID :");

        jLabel2.setText("First Name :");

        jLabel3.setText("Middle Name :");

        lbShortName.setText("Short Name :");

        jLabel5.setText("Telephone1 :");

        jLabel6.setText("Telephone2 :");

        jLabel7.setText("Mobile :");

        jLabel8.setText("Fax :");

        jLabel9.setText("Email :");

        jLabel10.setText("Address1 : ");

        jLabel11.setText("Address2 :");

        jLabel12.setText("City :");

        jLabel13.setText("State :");

        jLabel14.setText("Client type :");

        txtAccNum.setEditable(false);

        pnlAddTitle.setLayout(new java.awt.BorderLayout());

        lbTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Add New Client");
        pnlAddTitle.add(lbTitle, java.awt.BorderLayout.CENTER);

        lbFullName.setText("Full Name :");

        jLabel19.setText("Last Name :");

        jPanel1.setLayout(new java.awt.BorderLayout());

        lbDetailsOfContactPerson.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDetailsOfContactPerson.setText("Details of contact person :");
        jPanel1.add(lbDetailsOfContactPerson, java.awt.BorderLayout.CENTER);

        btnGrpClientType.add(rdBtOrganisation);
        rdBtOrganisation.setSelected(true);
        rdBtOrganisation.setText("Organisation");

        btnGrpClientType.add(rdBtIndividual);
        rdBtIndividual.setText("Individual");

        pnlModifyTitle.setLayout(new java.awt.BorderLayout());

        lbTitle1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle1.setText("Modify Client");
        pnlModifyTitle.add(lbTitle1, java.awt.BorderLayout.CENTER);

        btSave.setMnemonic('s');
        btSave.setText("Save");
        btSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btSaveKeyReleased(evt);
            }
        });
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveMouseReleased(evt);
            }
        });

        btDone.setMnemonic('d');
        btDone.setText("Done");
        btDone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btDoneKeyReleased(evt);
            }
        });
        btDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDoneMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlAddButtonsLayout = new javax.swing.GroupLayout(pnlAddButtons);
        pnlAddButtons.setLayout(pnlAddButtonsLayout);
        pnlAddButtonsLayout.setHorizontalGroup(
            pnlAddButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddButtonsLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btSave)
                .addGap(123, 123, 123)
                .addComponent(btDone))
        );
        pnlAddButtonsLayout.setVerticalGroup(
            pnlAddButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddButtonsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlAddButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSave)
                    .addComponent(btDone)))
        );

        btSaveChanges.setMnemonic('s');
        btSaveChanges.setText("Save Changes");
        btSaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveChangesMouseReleased(evt);
            }
        });

        btClose.setMnemonic('c');
        btClose.setText("Close");
        btClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCloseMouseReleased(evt);
            }
        });

        btDelete.setMnemonic('d');
        btDelete.setText("Delete");
        btDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDeleteMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlModifyButtonsLayout = new javax.swing.GroupLayout(pnlModifyButtons);
        pnlModifyButtons.setLayout(pnlModifyButtonsLayout);
        pnlModifyButtonsLayout.setHorizontalGroup(
            pnlModifyButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyButtonsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btSaveChanges)
                .addGap(50, 50, 50)
                .addComponent(btDelete)
                .addGap(72, 72, 72)
                .addComponent(btClose))
        );
        pnlModifyButtonsLayout.setVerticalGroup(
            pnlModifyButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyButtonsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlModifyButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSaveChanges)
                    .addComponent(btDelete)
                    .addComponent(btClose)))
        );

        pnlSearchMain.setVisible(false);
        pnlSearchMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbClientID)
                        .addGap(13, 13, 13)
                        .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(47, 47, 47)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addGap(44, 44, 44)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4)
                                .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(8, 8, 8)
                                .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(44, 44, 44)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addGap(24, 24, 24)
                                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(rdBtOrganisation))
                                    .addComponent(jLabel14))
                                .addGap(107, 107, 107)
                                .addComponent(rdBtIndividual)))
                        .addGap(90, 90, 90)
                        .addComponent(pnlSearchMain, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlModifyButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(pnlAddButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(txtTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addGap(2, 2, 2)
                                .addComponent(txtTelephone2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(txtContactFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(txtContactMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtContactLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbFullName)
                                .addGap(3, 3, 3)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lbShortName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClientID)
                    .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFullName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbShortName)
                        .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContactFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtContactMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtContactLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtTelephone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtOrganisation)
                            .addComponent(jLabel14)
                            .addComponent(rdBtIndividual)))
                    .addComponent(pnlSearchMain, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlModifyButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAddButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteMouseReleased
        // Add your handling code here:
    }//GEN-LAST:event_btDeleteMouseReleased

    private void btCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCloseMouseReleased
        // Add your handling code here:
        doneButtonPressed();
    }//GEN-LAST:event_btCloseMouseReleased

    private void btSaveChangesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveChangesMouseReleased
        // Add your handling code here:
        saveChangesButtonPressed();
    }//GEN-LAST:event_btSaveChangesMouseReleased

    private void btSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseReleased
        // Add your handling code here:
        saveButtonPressed();
    }//GEN-LAST:event_btSaveMouseReleased

    private void btSaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btSaveKeyReleased
        // Add your handling code here:
        saveButtonPressed();
    }//GEN-LAST:event_btSaveKeyReleased

    private void btDoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDoneMouseReleased
        // Add your handling code here:
        doneButtonPressed();
    }//GEN-LAST:event_btDoneMouseReleased

    private void btDoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btDoneKeyReleased
        // Add your handling code here:
        doneButtonPressed();
    }//GEN-LAST:event_btDoneKeyReleased
    
    
    /**
     *check data validation
     */
    private  boolean isDataValid(){
        if(txtName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the Full Name.","'Full Name' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtName.requestFocus();
            return false;
        }
        else if(txtContactFirstName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the First Name.","'First Name' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtContactFirstName.requestFocus();
            return false;
        }
          else if(txtContactLastName.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(this,"Please enter the Last Name.","'Last Name' is vacant:",JOptionPane.INFORMATION_MESSAGE);
                    txtContactLastName.requestFocus();
                    return false;
                }
          else if(txtTelephone1.getText().trim().equals("") && txtTelephone2.getText().trim().equals("") && txtMobile.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(this,"Please enter the Telephone No.","'Telephone 1' is vacant:",JOptionPane.INFORMATION_MESSAGE);
                    txtTelephone1.requestFocus();
                    return false;
                }
          else if(txtAddress1.getText().trim().equals("") && txtAddress2.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(this,"Please enter the Address.","'Address' is vacant:",JOptionPane.INFORMATION_MESSAGE);
                    txtAddress1.requestFocus();
                    return false;
                }
          else if(txtCity.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(this,"Please enter the City.","'City' is vacant:",JOptionPane.INFORMATION_MESSAGE);
                    txtCity.requestFocus();
                    return false;
                }
          else if(txtState.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(this,"Please enter the State.","'State' is vacant:",JOptionPane.INFORMATION_MESSAGE);
                    txtState.requestFocus();
                    return false;
                }
          else{
              return true;
          }
            }
    
    /** to get data from the user's end
     *
     */
    private ClientAccountObject getValuesFromInput() {
        Object[] dataArr = new Object[17];
        dataArr[0] = txtAccNum.getText();
        dataArr[1] = txtName.getText();
        dataArr[2] = txtShortName.getText();
        dataArr[3] = txtContactFirstName.getText();
        dataArr[4] = txtContactMiddleName.getText();
        dataArr[5] = txtContactLastName.getText();
        dataArr[6] = txtTelephone1.getText();
        dataArr[7] = txtTelephone2.getText();
        dataArr[8] = txtMobile.getText();
        dataArr[9] = txtFax.getText();
        dataArr[10] = txtEmail.getText();
        dataArr[11] = txtAddress1.getText();
        dataArr[12] = txtAddress2.getText();
        dataArr[13] = txtCity.getText();
        dataArr[14] = txtState.getText();
        if(rdBtOrganisation.isSelected())
            dataArr[15] = "1";
        else
            dataArr[15] = "0";
        dataArr[16] = "1";//status
        //pass on the data, in form of the model to the controller
        ClientAccountObject clObj = null;
        try{
            clObj = new ClientAccountObject(dataArr);        
        }catch(Exception e ){
            System.out.println(e);
        }      
        
        return clObj;
    }  
    
    private void save(ClientAccountObject clObj){
        //pass on the data, in form of the model to the controller
            clientAccountController.saveInDB(this, clObj);
    }
    
    private void update(ClientAccountObject clObj){
        clientAccountController.updateRecord(this, clObj);
    }
    
    /**
     *sets all fields in view to blank
     */
    public  void resetFields(){
         txtName.setText("");
         txtShortName.setText("");
         txtContactFirstName.setText("");
         txtContactMiddleName.setText("");
         txtContactLastName.setText("");
         txtTelephone1.setText("");
         txtTelephone2.setText("");
         txtMobile.setText("");
         txtFax.setText("");
         txtEmail.setText("");
         txtAddress1.setText("");
         txtAddress2.setText("");
         txtCity.setText("");
         txtState.setText("");
         rdBtOrganisation.setSelected(true);

    }    
    
    public void setAccNum(String accNum){
        txtAccNum.setText(accNum);
    }
    
  
    
    private void saveButtonPressed(){
        if(isDataValid()){
            ClientAccountObject clObj = getValuesFromInput();
            if(clObj==null){
                JOptionPane.showMessageDialog(this,"Data could not be saved","Sorry",JOptionPane.ERROR_MESSAGE);
                return ;
            }
            save(clObj);
        }
    }
    
    private void doneButtonPressed(){
        this.setVisible(false);
    }
    
    /**
     *method to set the text all JLabels from prperty file
     */
    private void setLabels(){
        lbClientID.setText(readProps.getVal("lbClientID"));
    }
    
    public void setFormToAdd(){
        pnlModifyTitle.setVisible(false);
        pnlModifyButtons.setVisible(false);
    }
    
    public void setFormToModify(){
        pnlAddTitle.setVisible(false);
        pnlAddButtons.setVisible(false);
        btDelete.setVisible(false);
        pnlSearchMain.setVisible(true);
        
        //add search panel
        srchPnl = new SearchPanel(clientAccountController.getClientName_ID(),new String[]{"Client Name","Client Account No."});
        pnlSearchMain.add(srchPnl,java.awt.BorderLayout.CENTER);                
        
        //add mouse listener
        srchPnl.btViewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSearchPanelViewRecordMouseReleased(evt);
            }
        });         
    } 
    
    private void setFieldsToModify(ClientAccountObject clObj){
        if(clObj==null){
            JOptionPane.showMessageDialog(this,"Please enter proper search criteria.","No match found:",JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Could not create an instance of ClientAccountObject");
            return ;
        }
        
        txtAccNum.setText(clObj.getAccNum().toString());
        txtName.setText(clObj.getName().toString());
        txtShortName.setText(clObj.getShortName().toString());
        txtContactFirstName.setText(clObj.getContactFirstName().toString());
        txtContactMiddleName.setText(clObj.getContactMiddleName().toString());
        txtContactLastName.setText(clObj.getContactLastName().toString());
        txtTelephone1.setText(clObj.getTelephone1().toString());
        txtTelephone2.setText(clObj.getTelephone2().toString());
        txtMobile.setText(clObj.getMobile().toString());
        txtFax.setText(clObj.getFax().toString());
        txtEmail.setText(clObj.getEmail().toString());
        txtAddress1.setText(clObj.getAddress1().toString());
        txtAddress2.setText(clObj.getAddress2().toString());
        txtCity.setText(clObj.getCity().toString());
        txtState.setText(clObj.getState().toString()); 
        if(clObj.getIsOrganization().toString().trim().equals("1"))
            rdBtOrganisation.setSelected(true);
        else
            rdBtIndividual.setSelected(true);
    }
    
    /**
     *initialises modification of records
     */
    private void saveChangesButtonPressed(){
        if(isDataValid()){
            ClientAccountObject clObj = getValuesFromInput();
            if(clObj==null){
                JOptionPane.showMessageDialog(this,"Data could not be modified","Sorry",JOptionPane.ERROR_MESSAGE);
                return ;
            }
            update(clObj);
            resetFields();
        }        
    }
    
    /** processes mouse released events on 'view record'
     * button on the search panel
     *
     */
    private void btSearchPanelViewRecordMouseReleased(java.awt.event.MouseEvent evt) {
        boolean id;
        if(srchPnl.cbSearch.getSelectedIndex()==0)
            id=false;
        else
            id=true;
        
        setFieldsToModify(clientAccountController.getClientObj(srchPnl.txtSearch.getText(),id));        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btDone;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSaveChanges;
    private javax.swing.ButtonGroup btnGrpClientType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbClientID;
    private javax.swing.JLabel lbDetailsOfContactPerson;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbShortName;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTitle1;
    private javax.swing.JPanel pnlAddButtons;
    public javax.swing.JPanel pnlAddTitle;
    private javax.swing.JPanel pnlModifyButtons;
    public javax.swing.JPanel pnlModifyTitle;
    private javax.swing.JPanel pnlSearchMain;
    private javax.swing.JRadioButton rdBtIndividual;
    private javax.swing.JRadioButton rdBtOrganisation;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactFirstName;
    private javax.swing.JTextField txtContactLastName;
    private javax.swing.JTextField txtContactMiddleName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtShortName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTelephone1;
    private javax.swing.JTextField txtTelephone2;
    // End of variables declaration//GEN-END:variables
    
    private ClientAccountController clientAccountController = null;
    private ReadPropertyFile readProps = null;
    private SearchPanel srchPnl = null;
}
