/*
 * DailyOrderBook.java
 *
 * Created on March 29, 2004, 2:36 PM
 */

package view;

/**
 *
 * @author  paawak
 */
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.GregorianCalendar;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import model.DailyOrderBookObject;
import model.database.ClientAccountDB;
import model.database.DailyOrderBookDB;
import model.database.TableListDB;
import utils.general.DateTimeUtils;
import utils.general.JComboUtils;
import utils.general.SearchPanel_NoButton;
import utils.general.ShowCalendar;
import utils.general.TxtFldValidation;
import controller.DailyOrderBookController;
import controller.Database;

public class DailyOrderBookView extends javax.swing.JPanel implements
        TableListDB, ClientAccountDB, DailyOrderBookDB {

    /** Creates new form DailyOrderBook */
    public DailyOrderBookView() {
        dt = new DateTimeUtils();
        dailyOrderBookController = new DailyOrderBookController();
        txtValid = new TxtFldValidation();
        initComponents();
        setSpecialFields();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTransactionType = new javax.swing.ButtonGroup();
        btGrSearchBy = new javax.swing.ButtonGroup();
        lbConsignmentNum = new javax.swing.JLabel();
        txtConsignmentNum = new javax.swing.JTextField();
        lbAccNum = new javax.swing.JLabel();
        cbCustName = new javax.swing.JComboBox();
        lbDestination = new javax.swing.JLabel();
        lbWeight = new javax.swing.JLabel();
        lbPackets = new javax.swing.JLabel();
        lbAmount = new javax.swing.JLabel();
        lbTransactionType = new javax.swing.JLabel();
        lbDeliveryDate = new javax.swing.JLabel();
        lbDeliveryTime = new javax.swing.JLabel();
        txtWeightKg = new javax.swing.JTextField();
        txtPackets = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtDeliveryDate = new javax.swing.JTextField();
        txtDeliveryTime = new javax.swing.JTextField();
        lbKg = new javax.swing.JLabel();
        lbConsignmentTime = new javax.swing.JLabel();
        txtConsignmentTime = new javax.swing.JTextField();
        txtWeightGm = new javax.swing.JTextField();
        lbGm = new javax.swing.JLabel();
        txtConsignmentDate = new javax.swing.JTextField();
        lbConsignmentDate = new javax.swing.JLabel();
        pnlAddTitle = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox(new String[]{"Local","Domestic","International"});
        pnlAddMode = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btDone = new javax.swing.JButton();
        pnlModifyMode = new javax.swing.JPanel();
        btSaveChanges = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scrPnAmountList = new javax.swing.JScrollPane();
        lstAmount = new javax.swing.JList();
        pnlRadioBts = new javax.swing.JPanel();
        rdBtCash = new javax.swing.JRadioButton();
        rdBtCredit = new javax.swing.JRadioButton();
        pnlBulkOrder = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtConsignmentNumFrom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtConsignmentNumTo = new javax.swing.JTextField();
        cbDestination = new javax.swing.JComboBox();
        pnlSearchMain = new javax.swing.JPanel();
        lbFromDate = new javax.swing.JLabel();
        txtFromDate = new javax.swing.JTextField();
        lbToDate = new javax.swing.JLabel();
        txtToDate = new javax.swing.JTextField();
        btDeleteRecords = new javax.swing.JButton();
        rdBtConsignmentNum = new javax.swing.JRadioButton();
        rdBtClientName = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        pnlSearchByClientName = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cbCustNameSearch = new javax.swing.JComboBox();
        pnlSearchByConsNum = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlModifyTitle = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pnlBulkOrderTitle = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btDateBackward = new javax.swing.JButton();
        btDateForward = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lbConsignmentNum.setText("Consignment No. :");

        lbAccNum.setText("Customer Name :");

        cbCustName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCustNameItemStateChanged(evt);
            }
        });

        lbDestination.setText("Destination :");

        lbWeight.setText("Weight :");

        lbPackets.setText("No. of packets :");

        lbAmount.setText("Amount :");

        lbTransactionType.setText("Transaction type :");

        lbDeliveryDate.setText("Delivery Date :");

        lbDeliveryTime.setText("Delivery Time :");

        txtWeightKg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWeightKgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWeightKgFocusLost(evt);
            }
        });

        txtPackets.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPacketsFocusGained(evt);
            }
        });

        txtAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAmount.setNextFocusableComponent(txtDeliveryDate);
        txtAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmountFocusLost(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
        });
        txtAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAmountMouseClicked(evt);
            }
        });

        txtDeliveryDate.setEditable(false);
        txtDeliveryDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDeliveryDateFocusGained(evt);
            }
        });
        txtDeliveryDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDeliveryDateMouseClicked(evt);
            }
        });

        lbKg.setText("Kg");

        lbConsignmentTime.setText("Consignment Time :");

        txtWeightGm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWeightGmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWeightGmFocusLost(evt);
            }
        });

        lbGm.setText("gm");

        txtConsignmentDate.setEditable(false);
        txtConsignmentDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtConsignmentDateMouseReleased(evt);
            }
        });

        lbConsignmentDate.setText("Consignment Date :");

        pnlAddTitle.setVisible(false);
        pnlAddTitle.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Daily Order Book");
        pnlAddTitle.add(jLabel17, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Type :");

        btSave.setMnemonic('s');
        btSave.setText("Save");
        btSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btSaveKeyReleased(evt);
            }
        });
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveMouseReleased(evt);
            }
        });

        btDone.setMnemonic('d');
        btDone.setText("Done");
        btDone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btDoneKeyReleased(evt);
            }
        });
        btDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDoneMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlAddModeLayout = new javax.swing.GroupLayout(pnlAddMode);
        pnlAddMode.setLayout(pnlAddModeLayout);
        pnlAddModeLayout.setHorizontalGroup(
            pnlAddModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddModeLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btSave)
                .addGap(133, 133, 133)
                .addComponent(btDone))
        );
        pnlAddModeLayout.setVerticalGroup(
            pnlAddModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddModeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlAddModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSave)
                    .addComponent(btDone)))
        );

        pnlModifyMode.setVisible(false);

        btSaveChanges.setMnemonic('s');
        btSaveChanges.setText("Save Changes");
        btSaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveChangesMouseReleased(evt);
            }
        });

        btDelete.setMnemonic('d');
        btDelete.setText("Delete");
        btDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDeleteMouseReleased(evt);
            }
        });

        btClose.setMnemonic('c');
        btClose.setText("Close");
        btClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlModifyModeLayout = new javax.swing.GroupLayout(pnlModifyMode);
        pnlModifyMode.setLayout(pnlModifyModeLayout);
        pnlModifyModeLayout.setHorizontalGroup(
            pnlModifyModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyModeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btSaveChanges)
                .addGap(40, 40, 40)
                .addComponent(btDelete)
                .addGap(92, 92, 92)
                .addComponent(btClose))
        );
        pnlModifyModeLayout.setVerticalGroup(
            pnlModifyModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyModeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlModifyModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSaveChanges)
                    .addComponent(btDelete)
                    .addComponent(btClose)))
        );

        jLabel3.setText("YYYY/MM/DD");

        jLabel4.setText("HH:mm:ss");

        jLabel5.setText("HH:mm:ss");

        jLabel6.setText("YYYY/MM/DD");

        scrPnAmountList.setDoubleBuffered(true);
        scrPnAmountList.setVisible(false);

        lstAmount.setDoubleBuffered(true);
        lstAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lstAmountFocusLost(evt);
            }
        });
        lstAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstAmountKeyReleased(evt);
            }
        });
        lstAmount.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAmountValueChanged(evt);
            }
        });
        lstAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstAmountMouseReleased(evt);
            }
        });
        scrPnAmountList.setViewportView(lstAmount);

        btnGrpTransactionType.add(rdBtCash);
        rdBtCash.setText("Cash");

        btnGrpTransactionType.add(rdBtCredit);
        rdBtCredit.setSelected(true);
        rdBtCredit.setText("Credit");

        javax.swing.GroupLayout pnlRadioBtsLayout = new javax.swing.GroupLayout(pnlRadioBts);
        pnlRadioBts.setLayout(pnlRadioBtsLayout);
        pnlRadioBtsLayout.setHorizontalGroup(
            pnlRadioBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioBtsLayout.createSequentialGroup()
                .addComponent(rdBtCash)
                .addGap(132, 132, 132)
                .addComponent(rdBtCredit))
        );
        pnlRadioBtsLayout.setVerticalGroup(
            pnlRadioBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioBtsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlRadioBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtCash)
                    .addComponent(rdBtCredit)))
        );

        pnlBulkOrder.setVisible(false);

        jLabel8.setText("To :");

        txtConsignmentNumFrom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtConsignmentNumFrom.setText("1");
        txtConsignmentNumFrom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConsignmentNumFromFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConsignmentNumFromFocusLost(evt);
            }
        });

        jLabel9.setText("From :");

        txtConsignmentNumTo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtConsignmentNumTo.setText("1");
        txtConsignmentNumTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConsignmentNumToFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConsignmentNumToFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlBulkOrderLayout = new javax.swing.GroupLayout(pnlBulkOrder);
        pnlBulkOrder.setLayout(pnlBulkOrderLayout);
        pnlBulkOrderLayout.setHorizontalGroup(
            pnlBulkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBulkOrderLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addComponent(txtConsignmentNumFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(txtConsignmentNumTo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBulkOrderLayout.setVerticalGroup(
            pnlBulkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9)
            .addComponent(txtConsignmentNumFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8)
            .addComponent(txtConsignmentNumTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cbDestination.setEditable(true);
        fillDestinationCombo();

        pnlSearchMain.setVisible(false);

        lbFromDate.setText("From :");

        txtFromDate.setEditable(false);
        txtFromDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtFromDateMouseReleased(evt);
            }
        });

        lbToDate.setText("To :");

        txtToDate.setEditable(false);
        txtToDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtToDateMouseReleased(evt);
            }
        });

        btDeleteRecords.setText("Delete Records");
        btDeleteRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDeleteRecordsMouseReleased(evt);
            }
        });

        btGrSearchBy.add(rdBtConsignmentNum);
        rdBtConsignmentNum.setSelected(true);
        rdBtConsignmentNum.setText("Consignment No.");
        rdBtConsignmentNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rdBtConsignmentNumMouseReleased(evt);
            }
        });

        btGrSearchBy.add(rdBtClientName);
        rdBtClientName.setText("Client Name");
        rdBtClientName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rdBtClientNameMouseReleased(evt);
            }
        });

        jLabel13.setText("Search By :");

        pnlSearchByClientName.setVisible(false);

        jLabel14.setText("Client Name :");

        cbCustNameSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCustNameSearchItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchByClientNameLayout = new javax.swing.GroupLayout(pnlSearchByClientName);
        pnlSearchByClientName.setLayout(pnlSearchByClientNameLayout);
        pnlSearchByClientNameLayout.setHorizontalGroup(
            pnlSearchByClientNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchByClientNameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addGap(38, 38, 38)
                .addComponent(cbCustNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSearchByClientNameLayout.setVerticalGroup(
            pnlSearchByClientNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchByClientNameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlSearchByClientNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cbCustNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlSearchByConsNum.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Consignment Numbers :");

        javax.swing.GroupLayout pnlSearchMainLayout = new javax.swing.GroupLayout(pnlSearchMain);
        pnlSearchMain.setLayout(pnlSearchMainLayout);
        pnlSearchMainLayout.setHorizontalGroup(
            pnlSearchMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbFromDate)
                .addGap(16, 16, 16)
                .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbToDate)
                .addGap(25, 25, 25)
                .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel13))
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(rdBtConsignmentNum)
                .addGap(7, 7, 7)
                .addComponent(rdBtClientName))
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(pnlSearchByClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(pnlSearchByConsNum, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btDeleteRecords))
        );
        pnlSearchMainLayout.setVerticalGroup(
            pnlSearchMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchMainLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlSearchMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFromDate)
                    .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbToDate)
                    .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addGap(15, 15, 15)
                .addGroup(pnlSearchMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtConsignmentNum)
                    .addComponent(rdBtClientName))
                .addGap(7, 7, 7)
                .addComponent(pnlSearchByClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(pnlSearchByConsNum, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btDeleteRecords))
        );

        pnlModifyTitle.setVisible(false);
        pnlModifyTitle.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Modify Daily Order Book");
        pnlModifyTitle.add(jLabel18, java.awt.BorderLayout.CENTER);

        pnlBulkOrderTitle.setVisible(false);
        pnlBulkOrderTitle.setLayout(new java.awt.BorderLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Daily Order Book: Bulk Order");
        pnlBulkOrderTitle.add(jLabel19, java.awt.BorderLayout.CENTER);

        btDateBackward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backward.JPG"))); // NOI18N
        btDateBackward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDateBackwardMouseReleased(evt);
            }
        });

        btDateForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forward.JPG"))); // NOI18N
        btDateForward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDateForwardMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBulkOrderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbConsignmentDate)
                            .addComponent(lbConsignmentTime)
                            .addComponent(lbConsignmentNum)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPackets)
                                    .addComponent(lbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTransactionType)
                                    .addComponent(lbDeliveryDate)
                                    .addComponent(lbDeliveryTime)
                                    .addComponent(lbAmount))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtConsignmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btDateForward, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cbCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(pnlBulkOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrPnAmountList, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lbKg))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(pnlSearchMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtWeightKg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtPackets, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDeliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(lbGm))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtConsignmentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(pnlRadioBts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(pnlModifyMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(btDateBackward, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(txtConsignmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(txtWeightGm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(pnlAddMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBulkOrderTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsignmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDateForward, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(cbCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlBulkOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(cbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(scrPnAmountList, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lbKg))
                    .addComponent(pnlSearchMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(txtWeightKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(txtPackets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(txtDeliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lbGm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtConsignmentNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(txtDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(pnlRadioBts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(pnlModifyMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel6))
                    .addComponent(btDateBackward, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtConsignmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(txtWeightGm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbAccNum))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbConsignmentDate)
                        .addGap(15, 15, 15)
                        .addComponent(lbConsignmentTime)
                        .addGap(15, 15, 15)
                        .addComponent(lbConsignmentNum)
                        .addGap(65, 65, 65)
                        .addComponent(lbDestination)
                        .addGap(35, 35, 35)
                        .addComponent(lbWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbPackets)
                        .addGap(45, 45, 45)
                        .addComponent(lbAmount)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lbTransactionType)
                                .addGap(45, 45, 45)
                                .addComponent(lbDeliveryDate)
                                .addGap(25, 25, 25)
                                .addComponent(lbDeliveryTime))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(pnlAddMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btDateBackwardMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_btDateBackwardMouseReleased
        // Add your handling code here:
        txtConsignmentDate.setText(getPrevBackDate(
                txtConsignmentDate.getText(), -1));
    }// GEN-LAST:event_btDateBackwardMouseReleased

    private void btDateForwardMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_btDateForwardMouseReleased
        // Add your handling code here:
        txtConsignmentDate.setText(getPrevBackDate(
                txtConsignmentDate.getText(), 1));
    }// GEN-LAST:event_btDateForwardMouseReleased

    private void cbCustNameItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-
        // FIRST
        // :
        // event_cbCustNameItemStateChanged
        // Add your handling code here:
        cbCustName.setToolTipText(cbCustName.getSelectedItem().toString());
    }// GEN-LAST:event_cbCustNameItemStateChanged

    private void lstAmountKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:
        // event_lstAmountKeyReleased
        // Add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            amtListItemSelected();
            hidePriceList();
        }
    }// GEN-LAST:event_lstAmountKeyReleased

    private void txtConsignmentNumToFocusGained(java.awt.event.FocusEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_txtConsignmentNumToFocusGained
        // Add your handling code here:
        txtConsignmentNumTo.selectAll();
    }// GEN-LAST:event_txtConsignmentNumToFocusGained

    private void txtConsignmentNumFromFocusGained(java.awt.event.FocusEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_txtConsignmentNumFromFocusGained
        // Add your handling code here:
        txtConsignmentNumFrom.selectAll();
    }// GEN-LAST:event_txtConsignmentNumFromFocusGained

    private void rdBtConsignmentNumMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_rdBtConsignmentNumMouseReleased
        // Add your handling code here:
        findSearchCriteria();
    }// GEN-LAST:event_rdBtConsignmentNumMouseReleased

    private void rdBtClientNameMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_rdBtClientNameMouseReleased
        // Add your handling code here:
        findSearchCriteria();
    }// GEN-LAST:event_rdBtClientNameMouseReleased

    private void btDeleteRecordsMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_btDeleteRecordsMouseReleased
        // Add your handling code here:
        Object[] consignmentNos = srchPnl.listSearch.getSelectedValues();

        if (consignmentNos == null || consignmentNos.length == 0) {
            return;
        }

        int opt = JOptionPane.showConfirmDialog(this,
                "You are about to delete " + consignmentNos.length
                        + " record(s) permanently. Are you sure?",
                "Confirm delete", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {// user chooses to delete
            int recordsDeleted = consignmentNos.length;
            for (int i = 0; i < consignmentNos.length; i++) {
                if (!dailyOrderBookController.deleteRecord(consignmentNos[i])) {
                    recordsDeleted--;
                    JOptionPane.showMessageDialog(this,
                            "Record could not be deleted: Consignment No.: "
                                    + consignmentNos[i],
                            "Could not delete record...",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
            if (recordsDeleted > 0) {
                JOptionPane.showMessageDialog(this, recordsDeleted
                        + " Record(s) deleted successfully",
                        "Delete successful", JOptionPane.INFORMATION_MESSAGE);
                MachExpressFrame.INSTANCE.showDailyOrderBookModify();
            }
        }
    }// GEN-LAST:event_btDeleteRecordsMouseReleased

    private void cbCustNameSearchItemStateChanged(java.awt.event.ItemEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_cbCustNameSearchItemStateChanged
        // Add your handling code here:
        // fill cbInvoiceNum
        Object[] obj2 = dailyOrderBookController.getConsignmentNums(txtFromDate
                .getText(), txtToDate.getText(), cbCustNameSearch
                .getSelectedItem());
        if (obj2 == null || obj2.length == 0)
            JOptionPane.showMessageDialog(this,
                    "Please enter proper search criteria.", "No match found.",
                    JOptionPane.INFORMATION_MESSAGE);
        else
            srchPnl.fillListWithNewArr(obj2);
    }// GEN-LAST:event_cbCustNameSearchItemStateChanged

    private void txtToDateMouseReleased(java.awt.event.MouseEvent evt) {// GEN-
        // FIRST
        // :
        // event_txtToDateMouseReleased
        // Add your handling code here:
        ShowCalendar cal = new ShowCalendar(new java.awt.Frame(), true,
                txtToDate);
        cal.show();
        findSearchCriteria();
    }// GEN-LAST:event_txtToDateMouseReleased

    private void txtFromDateMouseReleased(java.awt.event.MouseEvent evt) {// GEN-
        // FIRST
        // :
        // event_txtFromDateMouseReleased
        // Add your handling code here:
        ShowCalendar cal = new ShowCalendar(new java.awt.Frame(), true,
                txtFromDate);
        cal.show();
        findSearchCriteria();
    }// GEN-LAST:event_txtFromDateMouseReleased

    private void txtConsignmentNumToFocusLost(java.awt.event.FocusEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_txtConsignmentNumToFocusLost
        // Add your handling code here:
        if (!txtValid.checkNumber(txtConsignmentNumTo)) {

        }
    }// GEN-LAST:event_txtConsignmentNumToFocusLost

    private void txtConsignmentNumFromFocusLost(java.awt.event.FocusEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_txtConsignmentNumFromFocusLost
        // Add your handling code here:
        if (!txtValid.checkNumber(txtConsignmentNumFrom)) {

        }
    }// GEN-LAST:event_txtConsignmentNumFromFocusLost

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:
        // event_txtAmountKeyReleased
        // Add your handling code here:
        if (evt.getKeyCode() == evt.VK_DOWN && lstAmount.isVisible()) {
            lstAmount.requestFocus();
            lstAmount.setSelectedIndex(0);
        }
    }// GEN-LAST:event_txtAmountKeyReleased

    private void txtDeliveryDateFocusGained(java.awt.event.FocusEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_txtDeliveryDateFocusGained
        // Add your handling code here:
        hidePriceList();
    }// GEN-LAST:event_txtDeliveryDateFocusGained

    private void lstAmountValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_lstAmountValueChanged
        // Add your handling code here:
        amtListItemSelected();
    }// GEN-LAST:event_lstAmountValueChanged

    private void lstAmountMouseReleased(java.awt.event.MouseEvent evt) {// GEN-
        // FIRST
        // :
        // event_lstAmountMouseReleased
        // Add your handling code here:
        amtListItemSelected();
    }// GEN-LAST:event_lstAmountMouseReleased

    private void txtAmountMouseClicked(java.awt.event.MouseEvent evt) {// GEN-
        // FIRST:
        // event_txtAmountMouseClicked
        // Add your handling code here:
        if (!scrPnAmountList.isVisible())
            showPriceList();
    }// GEN-LAST:event_txtAmountMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:
        // event_formMouseClicked
        // Add your handling code here:
        if (scrPnAmountList.isVisible())
            hidePriceList();
    }// GEN-LAST:event_formMouseClicked

    private void lstAmountFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:
        // event_lstAmountFocusLost
        // Add your handling code here:
        hidePriceList();
    }// GEN-LAST:event_lstAmountFocusLost

    private void txtAmountFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:
        // event_txtAmountFocusLost
        // Add your handling code here:

    }// GEN-LAST:event_txtAmountFocusLost

    private void txtWeightGmFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST
        // :
        // event_txtWeightGmFocusLost
        // Add your handling code here:
        if (!txtValid.checkNumber(txtWeightGm)) {

        }
    }// GEN-LAST:event_txtWeightGmFocusLost

    private void txtWeightKgFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST
        // :
        // event_txtWeightKgFocusLost
        // Add your handling code here:
        if (!txtValid.checkNumber(txtWeightKg)) {

        }
    }// GEN-LAST:event_txtWeightKgFocusLost

    private void btCloseMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST
        // :
        // event_btCloseMouseReleased
        // Add your handling code here:
        doneButtonPressed();
    }// GEN-LAST:event_btCloseMouseReleased

    private void btDeleteMouseReleased(java.awt.event.MouseEvent evt) {// GEN-
        // FIRST:
        // event_btDeleteMouseReleased
        // Add your handling code here:
        deleteButtonPressed();
    }// GEN-LAST:event_btDeleteMouseReleased

    private void btSaveChangesMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_btSaveChangesMouseReleased
        // Add your handling code here:
        saveChangeButtonPressed();
    }// GEN-LAST:event_btSaveChangesMouseReleased

    private void txtAmountFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST
        // :
        // event_txtAmountFocusGained
        // Add your handling code here:
        txtAmount.selectAll();
        showPriceList();
    }// GEN-LAST:event_txtAmountFocusGained

    private void txtPacketsFocusGained(java.awt.event.FocusEvent evt) {// GEN-
        // FIRST:
        // event_txtPacketsFocusGained
        // Add your handling code here:
        txtPackets.selectAll();
    }// GEN-LAST:event_txtPacketsFocusGained

    private void txtWeightGmFocusGained(java.awt.event.FocusEvent evt) {// GEN-
        // FIRST
        // :
        // event_txtWeightGmFocusGained
        // Add your handling code here:
        txtWeightGm.selectAll();
    }// GEN-LAST:event_txtWeightGmFocusGained

    private void txtWeightKgFocusGained(java.awt.event.FocusEvent evt) {// GEN-
        // FIRST
        // :
        // event_txtWeightKgFocusGained
        // Add your handling code here:
        txtWeightKg.selectAll();
    }// GEN-LAST:event_txtWeightKgFocusGained

    private void btDoneMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST
        // :
        // event_btDoneMouseReleased
        // Add your handling code here:
        doneButtonPressed();
    }// GEN-LAST:event_btDoneMouseReleased

    private void btDoneKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:
        // event_btDoneKeyReleased
        // Add your handling code here:
        doneButtonPressed();
    }// GEN-LAST:event_btDoneKeyReleased

    private void btSaveMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST
        // :
        // event_btSaveMouseReleased
        // Add your handling code here:
        saveButtonPressed();
    }// GEN-LAST:event_btSaveMouseReleased

    private void btSaveKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:
        // event_btSaveKeyReleased
        // Add your handling code here:
        saveButtonPressed();
    }// GEN-LAST:event_btSaveKeyReleased

    private void txtDeliveryDateMouseClicked(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_txtDeliveryDateMouseClicked
        // Add your handling code here:
        new ShowCalendar(new java.awt.Frame(), true, txtDeliveryDate).show();
    }// GEN-LAST:event_txtDeliveryDateMouseClicked

    private void txtConsignmentDateMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_txtConsignmentDateMouseReleased
        // Add your handling code here:
        new ShowCalendar(new java.awt.Frame(), true, txtConsignmentDate).show();
    }// GEN-LAST:event_txtConsignmentDateMouseReleased

    /**
     *sets some of the fields invisible so that new data can be entered
     */
    public void setFormToAdd() {
        pnlAddTitle.setVisible(true);
        // txtCustName.setVisible(false);
        // pnlModifyMode.setVisible(false);
        // pnlSearch.setVisible(false);
        /*
         * lbDeliveryDate.setVisible(false); txtDeliveryDate.setVisible(false);
         * lbDeliveryTime.setVisible(false);
         * txtDeliveryTime.setVisible(false);//
         */
    }

    /**
     *sets the form to modify mode
     */
    public void setFormToModify() {
        pnlModifyTitle.setVisible(true);
        pnlAddMode.setVisible(false);
        txtConsignmentTime.setEditable(false);
        pnlSearchMain.setVisible(true);
        // remove mouse listener from consignment date so that user cannot
        // modify
        /*
         * MouseListener[] msArr = txtConsignmentDate.getMouseListeners();
         * for(int i=0; i<msArr.length; i++)
         * txtConsignmentDate.removeMouseListener(msArr[i]);//
         */
        // add the search panel
        srchPnl = new SearchPanel_NoButton(dailyOrderBookController
                .getConsignmentNums(txtFromDate.getText(), txtToDate.getText()));
        pnlSearchByConsNum.add(srchPnl, java.awt.BorderLayout.CENTER);

        srchPnl.listSearch.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    // show record
                    if (srchPnl.listSearch.getSelectedValue() != null)
                        displayRecordFromList(srchPnl.listSearch
                                .getSelectedValue().toString());
                }
            }
        });

        pnlModifyMode.setVisible(true);
    }

    /**
     *to fill cbCustName combo with new elements. it removes the old elements if any
     */
    public void fillCustNameCombo(Object[] objArr) {
        JComboUtils.fillComboWithNewArray(cbCustName, objArr);
        cbCustName.setToolTipText(cbCustName.getSelectedItem().toString());
    }

    /**
     *to fill cbDestination combo with new elements. it removes the old elements if any
     */
    private void fillDestinationCombo() {
        JComboUtils.fillComboWithNewArray(cbDestination,
                dailyOrderBookController.getDestinationArr());
    }

    /**
     *to set the decimal & number fields to 0 and date/time to current date time
     */
    private void setSpecialFields() {
        txtConsignmentDate.setText(dt.getMySqlDate());
        txtConsignmentTime.setText(dt.getMySqlTime());
        /*
         * txtDeliveryDate.setText(dt.getMySqlDate());
         * txtDeliveryTime.setText(dt.getMySqlTime());//
         */
        txtWeightKg.setText("0");
        txtWeightGm.setText("0");
        txtPackets.setText("1");
        txtAmount.setText("0.00");
        // set date fields
        setDateFields();
    }

    /**
     * check data validation
     * 
     */
    private boolean isDataValid() {
        if (txtConsignmentDate.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Please enter the Consignment Date.",
                    "'Consignment Date' is vacant:",
                    JOptionPane.INFORMATION_MESSAGE);
            txtConsignmentDate.requestFocus();
            return false;
        } else if (txtConsignmentNum.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Please enter the Consignment Number.",
                    "'Consignment Number' is vacant:",
                    JOptionPane.INFORMATION_MESSAGE);
            txtConsignmentNum.requestFocus();
            return false;
        } else if (cbDestination.getSelectedItem().toString().trim().equals("")) {
            JOptionPane
                    .showMessageDialog(this, "Please enter the Destination.",
                            "'Destination' is vacant:",
                            JOptionPane.INFORMATION_MESSAGE);
            cbDestination.requestFocus();
            return false;
        } else if (!txtValid.checkNumber(txtPackets)) {
            return false;
        } else if (!txtValid.checkDecimal(txtAmount, pattern)) {
            return false;
        } else if (isZeroVal(txtWeightKg) && isZeroVal(txtWeightGm)) {
            JOptionPane.showMessageDialog(this, "Enter a non-zero number.",
                    "Value cannot be zero:", JOptionPane.INFORMATION_MESSAGE);
            txtWeightKg.requestFocus();
            return false;
        } else if (isZeroVal(txtPackets)) {
            JOptionPane.showMessageDialog(this, "Enter a non-zero number.",
                    "Value cannot be zero:", JOptionPane.INFORMATION_MESSAGE);
            txtPackets.requestFocus();
            return false;
        } else if (Float.parseFloat(txtAmount.getText()) == 0) {
            JOptionPane.showMessageDialog(this, "Enter a non-zero number.",
                    "Value cannot be zero:", JOptionPane.INFORMATION_MESSAGE);
            txtAmount.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private boolean isZeroVal(JTextField txtFld) {
        try {
            int num = Integer.parseInt(txtFld.getText());
            if (num == 0)
                return true;
            else
                return false;
        } catch (NumberFormatException e) {
            System.out.println(e);
            return true;
        }
    }

    private void doneButtonPressed() {
        this.setVisible(false);
    }

    /**
     * to get data from the user's end
     * 
     * 
     */
    private DailyOrderBookObject getValuesFromInput() {
        DailyOrderBookObject dlObj = null;
        Vector objVec = new Vector(DailyOrderBookDB.fields);
        objVec.add(txtConsignmentNum.getText());
        objVec.add(txtConsignmentDate.getText());
        objVec.add(txtConsignmentTime.getText());
        if (cbCustName.isVisible())
            objVec.add(cbCustName.getSelectedItem());
        else
            objVec.add(cbCustName.getSelectedItem());
        objVec.add(cbDestination.getSelectedItem().toString().trim());
        objVec.add(cbType.getSelectedItem());
        objVec.add(txtWeightKg.getText());
        objVec.add(txtWeightGm.getText());
        objVec.add(txtPackets.getText());
        objVec.add(txtAmount.getText());
        if (rdBtCredit.isSelected())
            objVec.add("1");
        else
            objVec.add("0");
        objVec.add(dailyOrderBookController.getEmplIDLoggedIn());// employeeid
        dt = new DateTimeUtils();
        objVec.add(dt.getMySqlDateTime());// entry date/time
        objVec.add(txtDeliveryDate.getText());// delivery date
        objVec.add(txtDeliveryTime.getText());// delivery time

        // pass on the data, in form of the model to the controller
        try {
            dlObj = new DailyOrderBookObject(objVec);
        } catch (Exception e) {
            System.out.println(e);
        }// */

        return dlObj;
    }

    /**
     *to add new record
     */
    private void saveButtonPressed() {
        if (isDataValid()) {
            // to get the id from the name of the client
            DailyOrderBookObject obj = getValuesFromInput();
            try {
                Object acc = clDB.queryOneElement(ClientAccountDB.accnum,
                        "WHERE " + ClientAccountDB.name + "='"
                                + obj.getAccNum() + "'");
                obj.setAccNum(acc);
            } catch (Exception e) {
                System.out.println(e);
            }
            if (pnlBulkOrder.isVisible()) {
                int from = Integer.parseInt(txtConsignmentNumFrom.getText());
                int to = Integer.parseInt(txtConsignmentNumTo.getText());
                Object prefix = obj.getConsignmentNum();
                for (; from <= to; from++) {
                    String consignmentNum = "" + prefix + from;
                    obj.setConsignmentNum(consignmentNum);
                    dailyOrderBookController.saveInDB(this, obj, true);
                }
                JOptionPane.showMessageDialog(this,
                        "Bulk data enterd by you has been saved.",
                        "Saved successfully:", JOptionPane.INFORMATION_MESSAGE);
            } else
                dailyOrderBookController.saveInDB(this, obj, false);
            // resetFields();
        }
    }

    /**
     *to modify existing record
     */
    private void saveChangeButtonPressed() {
        if (isDataValid()) {
            dailyOrderBookController.modifyRecord(this, getValuesFromInput(),
                    consNum);
            // resetFields();
        }
    }

    /**
     * sets all fields in view to blank
     * 
     */
    public void resetFields() {
        fillDestinationCombo();
        txtConsignmentNum.setText("");

        cbType.setSelectedIndex(0);
        cbDestination.setSelectedItem("");
        // setSpecialFields();
        rdBtCredit.setSelected(true);
        txtDeliveryDate.setText("");
        txtDeliveryTime.setText("");
        txtConsignmentNumFrom.setText("1");
        txtConsignmentNumTo.setText("1");
    }

    /**
     *populates all the fielda to modify mode
     */
    private void setFieldsToModify(DailyOrderBookObject dlObj) {
        if (dlObj == null) {
            JOptionPane.showMessageDialog(this,
                    "Please enter proper search criteria.", "No match found.",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        consNum = dlObj.getConsignmentNum();
        txtConsignmentNum.setText(dlObj.getConsignmentNum().toString());
        // get client name
        Object clientName = null;
        Database clAccDb = new Database(clientaccount);
        try {
            clientName = clAccDb.queryOneElement(ClientAccountDB.name, "WHERE "
                    + ClientAccountDB.accnum + "='" + dlObj.getAccNum() + "'");
        } catch (Exception e) {
        }
        cbCustName.setSelectedItem(clientName.toString());
        cbType.setSelectedItem(dlObj.getType());
        cbDestination.setSelectedItem(dlObj.getDestination());
        txtConsignmentDate.setText(dlObj.getConsignmentDate().toString());
        txtConsignmentTime.setText(dlObj.getConsignmentTime().toString());
        txtDeliveryDate.setText(dlObj.getDeliveryDate().toString());
        txtDeliveryTime.setText(dlObj.getDeliveryTime().toString());
        txtWeightKg.setText(dlObj.getWeightKg().toString());
        txtWeightGm.setText(dlObj.getWeightGram().toString());
        txtPackets.setText(dlObj.getPackets().toString());
        txtAmount.setText(dlObj.getAmount().toString());
        // populate
        int credit = Integer.parseInt(dlObj.getIsCredit().toString());
        if (credit == 1)
            rdBtCredit.setSelected(true);
        else
            rdBtCredit.setSelected(false);
    }

    /**
     *takes appropriate action on delete bt pressed
     */
    private void deleteButtonPressed() {
        if (txtConsignmentNum.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Select a recprd to delete.",
                    "No record selected", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int opt = JOptionPane.showConfirmDialog(this,
                "You are about to delete a record permanently. Are you sure?",
                "Confirm delete", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {// user chooses to delete
            if (dailyOrderBookController.deleteRecord(consNum))
                JOptionPane.showMessageDialog(this,
                        "Record deleted successfully", "Delete successful",
                        JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane
                        .showMessageDialog(
                                this,
                                "Record could not be deleted: enter proper search criteria",
                                "No record found corresponding your search criteria",
                                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showPriceList() {
        int weight = 1000 * Integer.parseInt(txtWeightKg.getText())
                + Integer.parseInt(txtWeightGm.getText());
        Vector vec = dailyOrderBookController.getSlabPrice(weight);

        if (vec.size() > 0) {
            lstAmount.setListData(vec);
            scrPnAmountList.setVisible(true);
            pnlRadioBts.setVisible(false);
        }
    }

    private void hidePriceList() {
        if (scrPnAmountList.isVisible())
            scrPnAmountList.setVisible(false);
        if (!pnlRadioBts.isVisible())
            pnlRadioBts.setVisible(true);
    }

    private void amtListItemSelected() {
        if (lstAmount.getSelectedIndex() != -1)
            txtAmount.setText(lstAmount.getSelectedValue().toString());
    }

    /**
     *sets form to bulk order mode
     */
    public void setFormToBulkOrder() {
        pnlBulkOrderTitle.setVisible(true);
        pnlBulkOrder.setVisible(true);
        lbConsignmentNum.setText(lbConsignmentNum.getText() + "     Prefix :");
    }

    /**
     * search by invoice num
     * 
     */
    private void searchByConsignmentNum() {
        // make pnlSearchByClientName invisible
        pnlSearchByClientName.setVisible(false);
        // fill cbInvoiceNum
        Object[] obj = dailyOrderBookController.getConsignmentNums(txtFromDate
                .getText(), txtToDate.getText());
        if (obj == null || obj.length == 0)
            JOptionPane.showMessageDialog(this,
                    "Please enter proper search criteria.", "No match found.",
                    JOptionPane.INFORMATION_MESSAGE);
        else
            srchPnl.fillListWithNewArr(obj);
    }

    /**
     * search by client names
     * 
     */
    private void searchByClientNames() {
        // make pnlSearchByClientName visible
        pnlSearchByClientName.setVisible(true);
        // fill cbClientName
        Object[] obj1 = dailyOrderBookController.getClientNames(txtFromDate
                .getText(), txtToDate.getText());
        if (obj1 == null || obj1.length == 0)
            JOptionPane.showMessageDialog(this,
                    "Please enter proper search criteria.", "No match found.",
                    JOptionPane.INFORMATION_MESSAGE);
        else {
            JComboUtils.fillComboWithNewArray(cbCustNameSearch, obj1);
            // fill cbInvoiceNum
            Object[] obj2 = dailyOrderBookController.getConsignmentNums(
                    txtFromDate.getText(), txtToDate.getText(),
                    cbCustNameSearch.getSelectedItem());
            if (obj2 == null || obj2.length == 0)
                JOptionPane.showMessageDialog(this,
                        "Please enter proper search criteria.",
                        "No match found.", JOptionPane.INFORMATION_MESSAGE);
            else
                srchPnl.fillListWithNewArr(obj2);
        }
    }

    /**
     * finds out the current search criteria chosen by the user: inv num/cust name and takes appropriate action
     * 
     */
    private void findSearchCriteria() {
        if (rdBtConsignmentNum.isSelected())
            searchByConsignmentNum();
        else
            searchByClientNames();
    }

    /**
     * displays the given invoice according to the selected item in the invoice num combo
     * 
     */
    private void displayRecordFromList(String consignmentNum) {
        DailyOrderBookObject obj = dailyOrderBookController
                .getDailyOrderBookRecord(consignmentNum);
        setFieldsToModify(obj);
    }

    /**
     * to set the txtFromDate to the 1st of the month and txtToDate to the current date
     * 
     * 
     */
    private void setDateFields() {
        // set date fields
        GregorianCalendar gCal = new GregorianCalendar();
        gCal.set(gCal.DATE, gCal.getMinimum(gCal.DATE));
        DateTimeUtils dt = new DateTimeUtils();
        txtFromDate.setText(dt.getFormattedDate(gCal.getTime(), "yyyy/MM/dd"));
        txtToDate.setText(dt.getMySqlDate());
    }

    /**
     *to get the previous date
     */
    private String getPrevBackDate(String date, int val) {
        DateTimeUtils dt = new DateTimeUtils();
        GregorianCalendar gCal = dt.getGrCalFromString(date);
        gCal.add(gCal.DATE, val);
        return dt.getFormattedDate(gCal.getTime(), "yyyy/MM/dd");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDateBackward;
    private javax.swing.JButton btDateForward;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btDeleteRecords;
    private javax.swing.JButton btDone;
    private javax.swing.ButtonGroup btGrSearchBy;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSaveChanges;
    private javax.swing.ButtonGroup btnGrpTransactionType;
    private javax.swing.JComboBox cbCustName;
    private javax.swing.JComboBox cbCustNameSearch;
    private javax.swing.JComboBox cbDestination;
    private javax.swing.JComboBox cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbAccNum;
    private javax.swing.JLabel lbAmount;
    private javax.swing.JLabel lbConsignmentDate;
    private javax.swing.JLabel lbConsignmentNum;
    private javax.swing.JLabel lbConsignmentTime;
    private javax.swing.JLabel lbDeliveryDate;
    private javax.swing.JLabel lbDeliveryTime;
    private javax.swing.JLabel lbDestination;
    private javax.swing.JLabel lbFromDate;
    private javax.swing.JLabel lbGm;
    private javax.swing.JLabel lbKg;
    private javax.swing.JLabel lbPackets;
    private javax.swing.JLabel lbToDate;
    private javax.swing.JLabel lbTransactionType;
    private javax.swing.JLabel lbWeight;
    private javax.swing.JList lstAmount;
    private javax.swing.JPanel pnlAddMode;
    private javax.swing.JPanel pnlAddTitle;
    private javax.swing.JPanel pnlBulkOrder;
    private javax.swing.JPanel pnlBulkOrderTitle;
    private javax.swing.JPanel pnlModifyMode;
    private javax.swing.JPanel pnlModifyTitle;
    private javax.swing.JPanel pnlRadioBts;
    private javax.swing.JPanel pnlSearchByClientName;
    private javax.swing.JPanel pnlSearchByConsNum;
    private javax.swing.JPanel pnlSearchMain;
    private javax.swing.JRadioButton rdBtCash;
    private javax.swing.JRadioButton rdBtClientName;
    private javax.swing.JRadioButton rdBtConsignmentNum;
    private javax.swing.JRadioButton rdBtCredit;
    private javax.swing.JScrollPane scrPnAmountList;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtConsignmentDate;
    private javax.swing.JTextField txtConsignmentNum;
    private javax.swing.JTextField txtConsignmentNumFrom;
    private javax.swing.JTextField txtConsignmentNumTo;
    private javax.swing.JTextField txtConsignmentTime;
    private javax.swing.JTextField txtDeliveryDate;
    private javax.swing.JTextField txtDeliveryTime;
    private javax.swing.JTextField txtFromDate;
    private javax.swing.JTextField txtPackets;
    private javax.swing.JTextField txtToDate;
    private javax.swing.JTextField txtWeightGm;
    private javax.swing.JTextField txtWeightKg;
    // End of variables declaration//GEN-END:variables

    private TxtFldValidation txtValid = null;

    /**
     *holds the patern for decimal num
     */
    private String pattern = "0.00";// to be read from property file
    private DailyOrderBookController dailyOrderBookController = null;
    private DateTimeUtils dt = null;

    /**
     *it holds the consignment no. for modificatiom: in modify mode, u can modify the consignment no. but need the old value to update the record
     */
    private Object consNum = null;

    private Database clDB = new Database(TableListDB.clientaccount);

    private SearchPanel_NoButton srchPnl = null;

}
