/*
 * EmployeePanel.java
 *
 * Created on March 31, 2004, 1:22 AM
 */

package view;

/**
 *
 * @author  paawak
 */

import javax.swing.*;
import java.util.*;

import utils.general.*;
import model.*;
import controller.*;
import model.database.*;

public class EmployeeView extends javax.swing.JPanel implements TableListDB{
    
    /** Creates new form EmployeePanel */
    public EmployeeView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtTelephone1 = new javax.swing.JTextField();
        txtTelephone2 = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        pnlAddTitle = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pnlModifyTitle = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pnlAddButtons = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btDone = new javax.swing.JButton();
        pnlModifyButtons = new javax.swing.JPanel();
        btSaveChanges = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        pnlEndDate = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        pnlSearchMain = new javax.swing.JPanel();

        jLabel1.setText("Employee ID :");

        jLabel2.setText("First Name :");

        jLabel3.setText("Middle Name :");

        jLabel4.setText("Last Name :");

        jLabel5.setText("Telephone1 :");

        jLabel6.setText("Telephone2 :");

        jLabel7.setText("Mobile :");

        jLabel8.setText("Fax :");

        jLabel9.setText("Email :");

        jLabel10.setText("Address1 : ");

        jLabel11.setText("Address2 :");

        jLabel12.setText("City :");

        jLabel13.setText("State :");

        jLabel14.setText("Date of birth :");

        jLabel15.setText("Start date :");

        txtEmployeeID.setEditable(false);
        txtEmployeeID.setText(smCntr.getID());

        txtDateOfBirth.setEditable(false);
        txtDateOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDateOfBirthMouseReleased(evt);
            }
        });

        txtStartDate.setEditable(false);
        txtStartDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtStartDateMouseReleased(evt);
            }
        });

        pnlAddTitle.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Add New Employee");
        pnlAddTitle.add(jLabel17, java.awt.BorderLayout.CENTER);

        pnlModifyTitle.setVisible(false);
        pnlModifyTitle.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Modify Employee");
        pnlModifyTitle.add(jLabel18, java.awt.BorderLayout.CENTER);

        btSave.setMnemonic('s');
        btSave.setText("Save");
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveMouseReleased(evt);
            }
        });

        btDone.setMnemonic('d');
        btDone.setText("Done");
        btDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDoneMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlAddButtonsLayout = new javax.swing.GroupLayout(pnlAddButtons);
        pnlAddButtons.setLayout(pnlAddButtonsLayout);
        pnlAddButtonsLayout.setHorizontalGroup(
            pnlAddButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddButtonsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btSave)
                .addGap(123, 123, 123)
                .addComponent(btDone))
        );
        pnlAddButtonsLayout.setVerticalGroup(
            pnlAddButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddButtonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlAddButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSave)
                    .addComponent(btDone)))
        );

        pnlModifyButtons.setVisible(false);

        btSaveChanges.setMnemonic('s');
        btSaveChanges.setText("Save Changes");
        btSaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveChangesMouseReleased(evt);
            }
        });

        btClose.setMnemonic('c');
        btClose.setText("Close");
        btClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlModifyButtonsLayout = new javax.swing.GroupLayout(pnlModifyButtons);
        pnlModifyButtons.setLayout(pnlModifyButtonsLayout);
        pnlModifyButtonsLayout.setHorizontalGroup(
            pnlModifyButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyButtonsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btSaveChanges)
                .addGap(60, 60, 60)
                .addComponent(btClose))
        );
        pnlModifyButtonsLayout.setVerticalGroup(
            pnlModifyButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyButtonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlModifyButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSaveChanges)
                    .addComponent(btClose)))
        );

        pnlEndDate.setVisible(false);

        jLabel16.setText("End date :");

        txtEndDate.setEditable(false);
        txtEndDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtEndDateMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlEndDateLayout = new javax.swing.GroupLayout(pnlEndDate);
        pnlEndDate.setLayout(pnlEndDateLayout);
        pnlEndDateLayout.setHorizontalGroup(
            pnlEndDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEndDateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addGap(10, 10, 10)
                .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlEndDateLayout.setVerticalGroup(
            pnlEndDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEndDateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlEndDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlSearchMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(47, 47, 47)
                                        .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel9)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel13)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(110, 110, 110)
                        .addComponent(pnlSearchMain, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlModifyButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAddButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtTelephone2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addGap(29, 229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlModifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelephone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(pnlEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSearchMain, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlModifyButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAddButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEndDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEndDateMouseReleased
        // Add your handling code here:
        new ShowCalendar(new java.awt.Frame(), true,  txtEndDate).show();
    }//GEN-LAST:event_txtEndDateMouseReleased

    private void txtStartDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStartDateMouseReleased
        // Add your handling code here:
        new ShowCalendar(new java.awt.Frame(), true,  txtStartDate).show();
    }//GEN-LAST:event_txtStartDateMouseReleased

    private void txtDateOfBirthMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateOfBirthMouseReleased
        // Add your handling code here:
        new ShowCalendar(new java.awt.Frame(), true,  txtDateOfBirth).show();
    }//GEN-LAST:event_txtDateOfBirthMouseReleased

    private void btSaveChangesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveChangesMouseReleased
        // Add your handling code here:
        saveChangesBtPressed();
    }//GEN-LAST:event_btSaveChangesMouseReleased

    private void btSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseReleased
        // Add your handling code here:
        saveBtPressed();
    }//GEN-LAST:event_btSaveMouseReleased

    private void btCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCloseMouseReleased
        // Add your handling code here:
        doneBtPressed();
    }//GEN-LAST:event_btCloseMouseReleased

    private void btDoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDoneMouseReleased
        // Add your handling code here:
        doneBtPressed();
    }//GEN-LAST:event_btDoneMouseReleased
    
    /**
     *sets the form to modify mode
     */
    public void setFormToModify(){
        //show proper title
        pnlAddTitle.setVisible(false); 
        pnlModifyTitle.setVisible(true);  
        //show proper buttons
        pnlAddButtons.setVisible(false); 
        pnlModifyButtons.setVisible(true);  
        pnlEndDate.setVisible(true);
        
        //add search panel
        srchPnl = new SearchPanel(cntrl.getEmplName_ID(),new String[]{"Employee Name","Employee ID"});
        pnlSearchMain.add(srchPnl,java.awt.BorderLayout.CENTER);                
        
        //add mouse listener
        srchPnl.btViewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSearchPanelViewRecordMouseReleased(evt);
            }
        });        
    }
    
    private void doneBtPressed(){
        this.setVisible(false); 
    }
    
    /**
     *takes appropriate action when save 
     *button is pressed in the add mode
     */
    private void saveBtPressed(){
        if(isDataValid()){
            //save in db
            boolean saved = cntrl.saveInDB(getValuesFromInput());
            if(saved){
                smCntr.updateMaxCount();
                JOptionPane.showMessageDialog(this,"Data enterd by you has been saved.","Saved successfully:",JOptionPane.INFORMATION_MESSAGE);
                clearInputs();
            }
            else
                JOptionPane.showMessageDialog(this,"Data enterd by you could not be saved. Please try again.","Sorry:",JOptionPane.ERROR_MESSAGE);
        }
    }    
    
    /**
     *takes appropriate action when save changes
     *button is pressed in the modify mode
     */
    private void saveChangesBtPressed(){
        if(isDataValid()){
            //update in db
            boolean saved = cntrl.modifyRecord(getValuesFromInput(),txtEmployeeID.getText());
            if(saved){
                JOptionPane.showMessageDialog(this,"Data enterd by you has been modified.","Modified successfully:",JOptionPane.INFORMATION_MESSAGE);
                clearInputs();
            }
            else
                JOptionPane.showMessageDialog(this,"Data enterd by you could not be modified. Please try again.","Sorry:",JOptionPane.ERROR_MESSAGE);
        }        
    }      
    
    /** check data validation
     *
     */
    private boolean isDataValid() {
        if(txtFirstName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the First Name.","'First Name' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtFirstName.requestFocus();
            return false;
        }
        else if(txtLastName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the Last Name.","'Last Name' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtLastName.requestFocus();
            return false;
        }
        else if(txtTelephone1.getText().trim().equals("") && txtTelephone2.getText().trim().equals("") && txtMobile.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the Telephone No.","'Telephone 1' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtTelephone1.requestFocus();
            return false;
        }
        else if(txtAddress1.getText().trim().equals("") && txtAddress2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the Address.","'Address' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtAddress1.requestFocus();
            return false;
        }
        else if(txtCity.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the City.","'City' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtCity.requestFocus();
            return false;
        }
        else if(txtState.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the State.","'State' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtState.requestFocus();
            return false;
        }
        else if(txtDateOfBirth.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the Date of Birth.","'Date of Birth' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtDateOfBirth.requestFocus();
            return false;
        }
        else if(txtStartDate.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the Start Date.","'Start Date' is vacant:",JOptionPane.INFORMATION_MESSAGE);
            txtStartDate.requestFocus();
            return false;
        }        
        else{
            return true;
        }
    }
    
    /**
     *gets data from the form and casts it into an 
     *instance of EmployeeObject
     */
    private EmployeeObject getValuesFromInput(){
        EmployeeObject empl = null;
        Vector vec = new Vector();
        //empl id
        vec.addElement(txtEmployeeID.getText());
        //first name
        vec.addElement(txtFirstName.getText());
        //middlename
        vec.addElement(txtMiddleName.getText());
        //last name
        vec.addElement(txtLastName.getText());
        //tele 1
        vec.addElement(txtTelephone1.getText());
        //tele 2
        vec.addElement(txtTelephone2.getText());
        //mobile
        vec.addElement(txtMobile.getText());
        //fax
        vec.addElement(txtFax.getText());
        //email
        vec.addElement(txtEmail.getText());
        //addr 1
        vec.addElement(txtAddress1.getText());
        //addr 2
        vec.addElement(txtAddress2.getText());
        //city
        vec.addElement(txtCity.getText());
        //state
        vec.addElement(txtState.getText());
        //dob
        vec.addElement(txtDateOfBirth.getText());
        //strt dt
        vec.addElement(txtStartDate.getText());
        
        if(txtEndDate.isVisible()){
            //end dt
            vec.addElement(txtEndDate.getText());
            //status
            if(txtEndDate.getText().trim().equals(""))
                vec.addElement("1");
            else
                vec.addElement("0");
        }
        else{
            //end dt
            vec.addElement("");
            //status
            vec.addElement("1");
        }
        
        //create an instance of Empl obj
        try{
            empl = new EmployeeObject(vec);
        }catch(Exception e){
        }
        
        return empl;
    }
    
    /**
     *clears all input fields
     */
    private void clearInputs(){
        Object[] obj = new Object[EmployeeDB.fields];
        obj[0]=smCntr.getID();
        for(int i=1;i<obj.length;i++)
            obj[i]="";        
        try{
            EmployeeObject empl = new EmployeeObject(obj);
            setFields(empl);
        }catch (Exception e){
        }
    }
    
    /**
     *processes mouse released events on 'view record'
     *button on the search panel
     */
    private void btSearchPanelViewRecordMouseReleased(java.awt.event.MouseEvent evt){
        boolean id;
        if(srchPnl.cbSearch.getSelectedIndex()==0)
            id=false;
        else
            id=true;
        
        setFields(cntrl.getEmployeeRecord(srchPnl.txtSearch.getText(),id));
    }
    
    /**
     *sets all the input fields from the record fetched from the database
     *and passed as an instance of EmployeeObject
     *if the instance of EmployeeObject is null, it outputs suitable message
     */
    private void setFields(EmployeeObject obj){
        //check for null value
        if(obj == null){
            JOptionPane.showMessageDialog(this,"Please search by the EmployeeID as there are multiple records corresponding to your search criteria.","Multiple records exists for the search criteria:",JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        //empl id
        txtEmployeeID.setText(obj.getEmployeeId().toString());
        //first name
        txtFirstName.setText(obj.getFirstName().toString());
        //middlename
        txtMiddleName.setText(obj.getMiddleName().toString());
        //last name
        txtLastName.setText(obj.getLastName().toString());
        //tele 1
        txtTelephone1.setText(obj.getTelephone1().toString());
        //tele 2
        txtTelephone2.setText(obj.getTelephone2().toString());
        //mobile
        txtMobile.setText(obj.getMobile().toString());
        //fax
        txtFax.setText(obj.getFax().toString());
        //email
        txtEmail.setText(obj.getEmail().toString());
        //addr 1
        txtAddress1.setText(obj.getAddress1().toString());
        //addr 2
        txtAddress2.setText(obj.getAddress2().toString());
        //city
        txtCity.setText(obj.getCity().toString());
        //state
        txtState.setText(obj.getState().toString());
        //dob
        txtDateOfBirth.setText(obj.getDateOfBirth().toString());
        //strt dt
        txtStartDate.setText(obj.getStartDate().toString());        
        //end dt
        txtEndDate.setText(obj.getEndDate().toString());        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDone;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSaveChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlAddButtons;
    private javax.swing.JPanel pnlAddTitle;
    private javax.swing.JPanel pnlEndDate;
    private javax.swing.JPanel pnlModifyButtons;
    private javax.swing.JPanel pnlModifyTitle;
    private javax.swing.JPanel pnlSearchMain;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTelephone1;
    private javax.swing.JTextField txtTelephone2;
    // End of variables declaration//GEN-END:variables
    
    private EmployeeController cntrl = new EmployeeController();
    private SemaphoresController smCntr = new SemaphoresController(employee);
    private SearchPanel srchPnl = null;

}
