
package view;

import java.awt.*;
import javax.swing.*;
import java.util.GregorianCalendar;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

import controller.*;
import view.controller.*;

/**
 *
 * @author  paawak
 */
public class MachExpressFrame extends javax.swing.JFrame implements Runnable{
    
    public static final MachExpressFrame INSTANCE = new MachExpressFrame();
    
    private MachExpressFrame() {      
        initComponents();        
        time=new Thread(this);
        time.start();

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDateTime = new javax.swing.JPanel();
        lblDateTime = new javax.swing.JLabel();
        jScrollPanelHolder = new javax.swing.JScrollPane();
        jPnlStatus = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnDailyOrderBook = new javax.swing.JMenu();
        mnDailyOrderBookNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnDailyOrderBookModify = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnDailyOrderBokkBulkOrder = new javax.swing.JMenuItem();
        mnMonthRoll = new javax.swing.JMenu();
        mnMonthRollNew = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        mnMonthRollPageSettings = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        mnTDSTaxSettings = new javax.swing.JMenuItem();
        jMnTillDate = new javax.swing.JMenu();
        jMnInvoice = new javax.swing.JMenu();
        mnClient = new javax.swing.JMenu();
        mnNewClient = new javax.swing.JMenuItem();
        mnModifyClient = new javax.swing.JMenuItem();
        mnEmployee = new javax.swing.JMenu();
        mnEmployeeNew = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        mnEmployeeModify = new javax.swing.JMenuItem();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mach Express");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTitle.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Bookman Old Style", 1, 36));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Mach Express");
        pnlTitle.add(lblTitle, java.awt.BorderLayout.CENTER);

        pnlDateTime.setLayout(new java.awt.BorderLayout(50, 0));

        lblDateTime.setFont(new java.awt.Font("Lucida Console", 1, 14));
        lblDateTime.setText("Thursday, December 11, 2003 04:21:20 AM");
        lblDateTime.setText(dateFormatter.format(gCal.getTime()));
        pnlDateTime.add(lblDateTime, java.awt.BorderLayout.CENTER);

        pnlTitle.add(pnlDateTime, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlTitle);

        jScrollPanelHolder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPanelHolder.setMinimumSize(new java.awt.Dimension(500, 500));
        jScrollPanelHolder.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jScrollPanelHolder.setOpaque(false);
        getContentPane().add(jScrollPanelHolder);

        jPnlStatus.setLayout(new javax.swing.BoxLayout(jPnlStatus, javax.swing.BoxLayout.X_AXIS));

        jPnlStatus.setPreferredSize(new java.awt.Dimension(50, 28));
        jPnlStatus.setMinimumSize(new java.awt.Dimension(20, 28));
        lblStatus.setText("Status:");
        lblStatus.setFont(new java.awt.Font("Dialog", 0, 12));
        lblStatus.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jPnlStatus.add(lblStatus);

        txtStatus.setEditable(false);
        txtStatus.setText(" ");
        jPnlStatus.add(txtStatus);

        getContentPane().add(jPnlStatus);

        mnDailyOrderBook.setMnemonic('d');
        mnDailyOrderBook.setText("DailyOrderBook");
        mnDailyOrderBookNew.setMnemonic('n');
        mnDailyOrderBookNew.setText("New");
        mnDailyOrderBookNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnDailyOrderBookNewKeyReleased(evt);
            }
        });
        mnDailyOrderBookNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnDailyOrderBookNewMouseReleased(evt);
            }
        });

        mnDailyOrderBook.add(mnDailyOrderBookNew);

        mnDailyOrderBook.add(jSeparator1);

        mnDailyOrderBookModify.setMnemonic('a');
        mnDailyOrderBookModify.setText("Modify");
        mnDailyOrderBookModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnDailyOrderBookModifyMouseReleased(evt);
            }
        });

        mnDailyOrderBook.add(mnDailyOrderBookModify);

        mnDailyOrderBook.add(jSeparator2);

        mnDailyOrderBokkBulkOrder.setText("Bulk Order");
        mnDailyOrderBokkBulkOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnDailyOrderBokkBulkOrderMouseReleased(evt);
            }
        });

        mnDailyOrderBook.add(mnDailyOrderBokkBulkOrder);

        jMenuBar1.add(mnDailyOrderBook);

        mnMonthRoll.setMnemonic('m');
        mnMonthRoll.setText("Month Roll");
        mnMonthRollNew.setMnemonic('n');
        mnMonthRollNew.setText("New");
        mnMonthRollNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnMonthRollNewMouseReleased(evt);
            }
        });

        mnMonthRoll.add(mnMonthRollNew);

        mnMonthRoll.add(jSeparator4);

        mnMonthRollPageSettings.setText("Page Setup");
        mnMonthRollPageSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnMonthRollPageSettingsMouseReleased(evt);
            }
        });

        mnMonthRoll.add(mnMonthRollPageSettings);

        mnMonthRoll.add(jSeparator5);

        mnTDSTaxSettings.setMnemonic('t');
        mnTDSTaxSettings.setText("TDS/Tax Setting");
        mnTDSTaxSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnTDSTaxSettingsMouseReleased(evt);
            }
        });

        mnMonthRoll.add(mnTDSTaxSettings);

        jMenuBar1.add(mnMonthRoll);

        jMnTillDate.setMnemonic('t');
        jMnTillDate.setText("Transactions Details");
        jMnTillDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMnTillDateMouseReleased(evt);
            }
        });

        jMenuBar1.add(jMnTillDate);

        jMnInvoice.setMnemonic('i');
        jMnInvoice.setText("Invoice");
        jMnInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMnInvoiceMouseReleased(evt);
            }
        });

        jMenuBar1.add(jMnInvoice);

        mnClient.setMnemonic('c');
        mnClient.setText("Client");
        mnNewClient.setMnemonic('a');
        mnNewClient.setText("New");
        mnNewClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnNewClientKeyReleased(evt);
            }
        });
        mnNewClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnNewClientMouseReleased(evt);
            }
        });

        mnClient.add(mnNewClient);

        mnModifyClient.setText("Modify");
        mnModifyClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnModifyClientMouseReleased(evt);
            }
        });

        mnClient.add(mnModifyClient);

        jMenuBar1.add(mnClient);

        mnEmployee.setMnemonic('e');
        mnEmployee.setText("Employee");
        mnEmployeeNew.setMnemonic('n');
        mnEmployeeNew.setText("New");
        mnEmployeeNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnEmployeeNewKeyReleased(evt);
            }
        });
        mnEmployeeNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnEmployeeNewMouseReleased(evt);
            }
        });

        mnEmployee.add(mnEmployeeNew);

        mnEmployee.add(jSeparator3);

        mnEmployeeModify.setMnemonic('m');
        mnEmployeeModify.setText("Modify");
        mnEmployeeModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnEmployeeModifyMouseReleased(evt);
            }
        });

        mnEmployee.add(mnEmployeeModify);

        jMenuBar1.add(mnEmployee);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void mnTDSTaxSettingsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTDSTaxSettingsMouseReleased
        // Add your handling code here:
        showMonthRollTDSTaxSettings();
    }//GEN-LAST:event_mnTDSTaxSettingsMouseReleased

    private void mnMonthRollPageSettingsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMonthRollPageSettingsMouseReleased
        // Add your handling code here:
        showMonthRollPageSettings();
    }//GEN-LAST:event_mnMonthRollPageSettingsMouseReleased

    private void mnMonthRollNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMonthRollNewMouseReleased
        // Add your handling code here:
        showMonthRoll();
    }//GEN-LAST:event_mnMonthRollNewMouseReleased

    private void mnEmployeeModifyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnEmployeeModifyMouseReleased
        // Add your handling code here:
        showEmployeeModify();
    }//GEN-LAST:event_mnEmployeeModifyMouseReleased

    private void mnDailyOrderBokkBulkOrderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDailyOrderBokkBulkOrderMouseReleased
        // Add your handling code here:
        showBulkDailyOrderBook();
    }//GEN-LAST:event_mnDailyOrderBokkBulkOrderMouseReleased

    private void mnModifyClientMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnModifyClientMouseReleased
        // Add your handling code here:
        showClientModify();
    }//GEN-LAST:event_mnModifyClientMouseReleased

    private void mnDailyOrderBookModifyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDailyOrderBookModifyMouseReleased
        // Add your handling code here:
        showDailyOrderBookModify();
    }//GEN-LAST:event_mnDailyOrderBookModifyMouseReleased

    private void jMnInvoiceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMnInvoiceMouseReleased
        // Add your handling code here:
        showInvoiceNew();
    }//GEN-LAST:event_jMnInvoiceMouseReleased

    private void jMnTillDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMnTillDateMouseReleased
        // Add your handling code here:
        showTransactionDetails();
    }//GEN-LAST:event_jMnTillDateMouseReleased

    private void mnNewClientMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnNewClientMouseReleased
        // Add your handling code here:
        showClientAccountNew();
    }//GEN-LAST:event_mnNewClientMouseReleased

    private void mnNewClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnNewClientKeyReleased
        // Add your handling code here:
        showClientAccountNew();
    }//GEN-LAST:event_mnNewClientKeyReleased

    private void mnEmployeeNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnEmployeeNewMouseReleased
        // Add your handling code here:
        showEmployeeNew();
    }//GEN-LAST:event_mnEmployeeNewMouseReleased

    private void mnEmployeeNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnEmployeeNewKeyReleased
        // Add your handling code here:
        showEmployeeNew();
    }//GEN-LAST:event_mnEmployeeNewKeyReleased

    private void mnDailyOrderBookNewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnDailyOrderBookNewKeyReleased
        // Add your handling code here:
        showDailyOrderBookNew();
    }//GEN-LAST:event_mnDailyOrderBookNewKeyReleased

    private void mnDailyOrderBookNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDailyOrderBookNewMouseReleased
        // Add your handling code here:
        showDailyOrderBookNew();
    }//GEN-LAST:event_mnDailyOrderBookNewMouseReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Add your handling code here:
        LoginDialog login = new LoginDialog(this,true);
        login.txtLoginID.requestFocus();
        login.show();  //*/       
    }//GEN-LAST:event_formWindowOpened
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        // Add your handling code here:
        int logout=JOptionPane.showConfirmDialog(this,"Are you sure you want to logout?","Logout?",JOptionPane.YES_NO_OPTION);
        if(logout==JOptionPane.YES_OPTION)
            System.exit(0);         
    }//GEN-LAST:event_exitForm

    /** @param args the command line arguments
     *
     *
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnInvoice;
    private javax.swing.JMenu jMnTillDate;
    private javax.swing.JPanel jPnlStatus;
    public static javax.swing.JScrollPane jScrollPanelHolder;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu mnClient;
    private javax.swing.JMenuItem mnDailyOrderBokkBulkOrder;
    private javax.swing.JMenu mnDailyOrderBook;
    private javax.swing.JMenuItem mnDailyOrderBookModify;
    private javax.swing.JMenuItem mnDailyOrderBookNew;
    private javax.swing.JMenu mnEmployee;
    private javax.swing.JMenuItem mnEmployeeModify;
    private javax.swing.JMenuItem mnEmployeeNew;
    private javax.swing.JMenuItem mnModifyClient;
    private javax.swing.JMenu mnMonthRoll;
    private javax.swing.JMenuItem mnMonthRollNew;
    private javax.swing.JMenuItem mnMonthRollPageSettings;
    private javax.swing.JMenuItem mnNewClient;
    private javax.swing.JMenuItem mnTDSTaxSettings;
    private javax.swing.JPanel pnlDateTime;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
  
    private GregorianCalendar gCal = new GregorianCalendar();
    
    private Thread time;
    
    private Locale locale = new Locale("en","IN");//'en'--english; 'IN'--INDIA

    private DateFormat dateFormatter = DateFormat.getDateTimeInstance(DateFormat.FULL,DateFormat.MEDIUM,locale);
    
    private DailyOrderBookViewController cntlrBook = new DailyOrderBookViewController();
    
    private EmployeeViewController cntlrEmp = new EmployeeViewController();
    
    private ClientAccountViewController cntlrClient = new ClientAccountViewController();
    
    private MonthRollViewController cntlrMonthRoll = new MonthRollViewController();
    
    private InvoiceViewController cntlrInvoice = new InvoiceViewController();
    
    private void showDailyOrderBookNew(){                
        setBodyPanel(cntlrBook.getNewDailyOrderBookPanel()); 
    }
    
    public void showDailyOrderBookModify(){                
        setBodyPanel(cntlrBook.getModifyDailyOrderBookPanel()); 
    }    
    
    private void showBulkDailyOrderBook(){
        setBodyPanel(cntlrBook.getBulkDailyOrderBookPanel()); 
    }
    
    private void showEmployeeNew(){
        setBodyPanel(cntlrEmp.getNewEmployeePanel());
    }
    
    private void showEmployeeModify(){
        setBodyPanel(cntlrEmp.getModifyEmployeePanel());
    }
    
    private void showClientAccountNew(){
        setBodyPanel(cntlrClient.getNewClientAccountPanel());
    }    
    
    private void showClientModify(){
        setBodyPanel(cntlrClient.getModifyClientAccountPanel());
    }
    
    private void showMonthRoll(){
        setBodyPanel(cntlrMonthRoll.getNewMonthRollPanel());
    }
    
    private void showTransactionDetails(){
        setBodyPanel(new TransactionDetailsView());
    }   
    
    private void showInvoiceNew(){
        setBodyPanel(cntlrInvoice.getNewInvoicePanel());
    } 
    
    private void showMonthRollPageSettings(){
        setBodyPanel(new MonthRollPageSettingsView());
    }
    
    private void showMonthRollTDSTaxSettings(){
        setBodyPanel(new MonthRollTDSTaxSettingsView());
    }
             
    private void setBodyPanel(JPanel Panel) {
        jScrollPanelHolder.getViewport().setView(Panel);
    }    
    

    /** When an object implementing interface <code>Runnable</code> is used
     * to create a thread, starting the thread causes the object's
     * <code>run</code> method to be called in that separately executing
     * thread.
     * <p>
     * The general contract of the method <code>run</code> is that it may
     * take any action whatsoever.
     *
     * @see     java.lang.Thread#run()
     *
     */
    public void run() {
        Thread t = Thread.currentThread();
        
        while(time == t){
            try{
                Thread.currentThread().sleep(1000);
            }catch(InterruptedException e){}
            
        gCal.add(gCal.SECOND, 1);        

        lblDateTime.setText(dateFormatter.format(gCal.getTime()));
                    
        }
        

    }
       
}
