/*
 * MonthRollView.java
 *
 * Created on 20 April 2004, 16:13
 */

package view;

/**
 *
 * @author  paawak
 */
import java.util.*;
import java.text.*;

import utils.general.*;
import model.*;
import controller.*;
import model.database.*;
import javax.swing.*;

public class MonthRollView extends javax.swing.JPanel implements TableListDB, DailyOrderBookDB{
    
    /** Creates new form MonthRollView */
    public MonthRollView() {
        initComponents();
        setDateFields();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lbFromDate = new javax.swing.JLabel();
        txtFromDate = new javax.swing.JTextField();
        lbToDate = new javax.swing.JLabel();
        txtToDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArDetails = new javax.swing.JTextArea();
        btRoll = new javax.swing.JButton();
        btClose = new javax.swing.JButton();

        pnlTitle.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Month Rolling  For All Clients");
        pnlTitle.add(jLabel17, java.awt.BorderLayout.CENTER);

        lbFromDate.setText("From :");

        txtFromDate.setEditable(false);
        txtFromDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtFromDateMouseReleased(evt);
            }
        });

        lbToDate.setText("To :");

        txtToDate.setEditable(false);

        txtArDetails.setEditable(false);
        txtArDetails.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(txtArDetails);

        btRoll.setMnemonic('r');
        btRoll.setText("Roll");
        btRoll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btRollMouseReleased(evt);
            }
        });

        btClose.setMnemonic('c');
        btClose.setText("Close");
        btClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lbFromDate)
                .addGap(76, 76, 76)
                .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(lbToDate)
                .addGap(95, 95, 95)
                .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btRoll)
                .addGap(251, 251, 251)
                .addComponent(btClose))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFromDate)
                    .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbToDate)
                    .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRoll)
                    .addComponent(btClose)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCloseMouseReleased
        // Add your handling code here:
        closeButtonPressed();
    }//GEN-LAST:event_btCloseMouseReleased

    private void txtFromDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFromDateMouseReleased
        // Add your handling code here:
        ShowCalendar cal = new ShowCalendar(new java.awt.Frame(), true,  txtFromDate);
        cal.show();
        gCal = cal.getSelectedDate();
        setDateFields();        
    }//GEN-LAST:event_txtFromDateMouseReleased

    private void btRollMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRollMouseReleased
        // Add your handling code here:
        rollBtPressed();        
    }//GEN-LAST:event_btRollMouseReleased

    private void closeButtonPressed() {
        this.setVisible(false);
    }    
    
    public void resetFields() {
    }    
    
    private void setDateFields() {
        gCal.set(gCal.DATE,gCal.getMinimum(gCal.DATE));
        Date dt = gCal.getTime();
        String pattern = "dd MMMMMMMM, yyyy";//to be read from property file
        SimpleDateFormat formatter = new SimpleDateFormat(pattern);
        txtFromDate.setText(formatter.format(dt));
        gCal.set(gCal.DATE,gCal.getActualMaximum(gCal.DAY_OF_MONTH));
        dt = gCal.getTime();
        txtToDate.setText(formatter.format(dt));
    }
    
    private void rollBtPressed() {
        int returned = JOptionPane.showConfirmDialog(this,"Are you sure you want to proceed?","Confirm Roll Procedure",JOptionPane.YES_NO_OPTION);
        if(returned==JOptionPane.YES_OPTION){
            cntrl.roll(this, gCal.get(gCal.YEAR), gCal.get(gCal.MONTH)+1);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btRoll;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFromDate;
    private javax.swing.JLabel lbToDate;
    private javax.swing.JPanel pnlTitle;
    public javax.swing.JTextArea txtArDetails;
    private javax.swing.JTextField txtFromDate;
    private javax.swing.JTextField txtToDate;
    // End of variables declaration//GEN-END:variables

    /** holds the selected date
     *
     */
    private GregorianCalendar gCal = new GregorianCalendar();
    
    private MonthRollController cntrl = new MonthRollController();
        
}
