/*
 * MonthRollPageSettingsView.java
 *
 * Created on 11 May 2004, 20:25
 */

package view;

/**
 *
 * @author  paawak
 */
import javax.swing.*;

import controller.*;

public class MonthRollTDSTaxSettingsView extends javax.swing.JPanel {
    
    /** Creates new form MonthRollPageSettingsView */
    public MonthRollTDSTaxSettingsView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        frmTxtTDSPercent = new javax.swing.JFormattedTextField(new java.text.DecimalFormat("0.00"));
        jLabel2 = new javax.swing.JLabel();
        frmTxtTDSApplyAmt = new javax.swing.JFormattedTextField(new java.text.DecimalFormat("0.00"));
        btSave = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        frmTxtTaxPercent = new javax.swing.JFormattedTextField(new java.text.DecimalFormat("0.00"));
        lbFuelCharges = new javax.swing.JLabel();
        frmTxtFuelCharges = new javax.swing.JFormattedTextField(new java.text.DecimalFormat("0.00"));

        pnlTitle.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html><u>TDS/Tax Settings For Invoice File</u></html>");
        pnlTitle.add(jLabel17, java.awt.BorderLayout.CENTER);

        jLabel1.setText("TDS Percent :");

        frmTxtTDSPercent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtTDSPercent.setText(cnt.getTDSPercent());
        frmTxtTDSPercent.setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);

        jLabel2.setText("TDS Cut-off Amount :");

        frmTxtTDSApplyAmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtTDSApplyAmt.setText(cnt.getTDSApplyAmt());
        frmTxtTDSApplyAmt.setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);

        btSave.setMnemonic('s');
        btSave.setText("Save");
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveMouseReleased(evt);
            }
        });

        btClose.setMnemonic('c');
        btClose.setText("Close");
        btClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCloseMouseReleased(evt);
            }
        });

        jLabel3.setText("Tax Percent :");

        frmTxtTaxPercent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtTaxPercent.setText(cnt.getTaxPercent());
        frmTxtTaxPercent.setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);

        lbFuelCharges.setText("Fuel Charge :");

        frmTxtFuelCharges.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtFuelCharges.setText(cnt.getFuelCharge());
        frmTxtFuelCharges.setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(frmTxtTDSPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(frmTxtTDSApplyAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel3)
                .addGap(60, 60, 60)
                .addComponent(frmTxtTaxPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(lbFuelCharges)
                .addGap(60, 60, 60)
                .addComponent(frmTxtFuelCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(btSave)
                .addGap(133, 133, 133)
                .addComponent(btClose))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(frmTxtTDSPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(frmTxtTDSApplyAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(frmTxtTaxPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFuelCharges)
                    .addComponent(frmTxtFuelCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSave)
                    .addComponent(btClose)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCloseMouseReleased
        // Add your handling code here:
        btClosePressed();
    }//GEN-LAST:event_btCloseMouseReleased

    private void btSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseReleased
        // Add your handling code here:
        btSavePressed();
    }//GEN-LAST:event_btSaveMouseReleased
    
    private boolean isDataValid(){
        boolean flag = false;
        if(frmTxtTDSPercent.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Cannot be empty","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtTDSPercent.requestFocus();
        }
        else if(frmTxtTDSApplyAmt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Cannot be empty","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtTDSApplyAmt.requestFocus();
        }
        else if(Float.parseFloat(frmTxtTDSApplyAmt.getText().trim())==0){
            JOptionPane.showMessageDialog(this,"Cannot be zero","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtTDSApplyAmt.requestFocus();            
        }        
        else if(frmTxtTaxPercent.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Cannot be empty","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtTaxPercent.requestFocus();
        }
        else if (frmTxtFuelCharges.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Cannot be empty", "",
                    JOptionPane.INFORMATION_MESSAGE);
            frmTxtFuelCharges.requestFocus();
        }
        else {
            flag=true;
        }
        return flag;
    }
    
    private void btSavePressed() {
        if (isDataValid())
            try {
                if (cnt.updateTDSTaxSettings(new Object[] {
                        frmTxtTDSPercent.getText().trim(),
                        frmTxtTDSApplyAmt.getText().trim(),
                        frmTxtTaxPercent.getText().trim() })
                        && cnt.insertOrUpdateFuelCharges(frmTxtFuelCharges
                                .getText().trim())) {
                    JOptionPane.showMessageDialog(this,
                            "Data modified successfully", "Saved:",
                            JOptionPane.INFORMATION_MESSAGE);
                    // clearInputs();
                } else
                    JOptionPane.showMessageDialog(this,
                            "Data could not be modified", "Sorry:",
                            JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
    
//    private void clearInputs(){
//        frmTxtTDSPercent.setText("");
//        frmTxtTDSApplyAmt.setText("");
//        frmTxtTaxPercent.setText("");
//    }
    
    private void btClosePressed(){
        this.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btSave;
    private javax.swing.JFormattedTextField frmTxtFuelCharges;
    private javax.swing.JFormattedTextField frmTxtTDSApplyAmt;
    private javax.swing.JFormattedTextField frmTxtTDSPercent;
    private javax.swing.JFormattedTextField frmTxtTaxPercent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbFuelCharges;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
    
    private SettingsController cnt = new SettingsController();
}

