/*
 * MonthRollPageSettingsView.java
 *
 * Created on 11 May 2004, 20:25
 */

package view;

/**
 *
 * @author  paawak
 */
import javax.swing.*;

import controller.*;

public class MonthRollPageSettingsView extends javax.swing.JPanel {
    
    /** Creates new form MonthRollPageSettingsView */
    public MonthRollPageSettingsView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        frmTxtCols = new javax.swing.JFormattedTextField(new java.text.DecimalFormat("0"));
        jLabel2 = new javax.swing.JLabel();
        frmTxtLines = new javax.swing.JFormattedTextField(new java.text.DecimalFormat("0"));
        btSave = new javax.swing.JButton();
        btClose = new javax.swing.JButton();

        pnlTitle.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html><u>Page Settings For Invoice File</u></html>");
        pnlTitle.add(jLabel17, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Max. no. of characters in a column :");

        frmTxtCols.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtCols.setText(cnt.getCols());
        frmTxtCols.setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);

        jLabel2.setText("Max. no. of lines in a page :");

        frmTxtLines.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtLines.setText(cnt.getLines());
        frmTxtLines.setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);

        btSave.setMnemonic('s');
        btSave.setText("Save");
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveMouseReleased(evt);
            }
        });

        btClose.setMnemonic('c');
        btClose.setText("Close");
        btClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(btSave)
                        .addGap(57, 57, 57)
                        .addComponent(btClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(frmTxtLines, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(frmTxtCols, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(frmTxtCols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(frmTxtLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btClose)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCloseMouseReleased
        // Add your handling code here:
        btClosePressed();
    }//GEN-LAST:event_btCloseMouseReleased

    private void btSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseReleased
        // Add your handling code here:
        btSavePressed();
    }//GEN-LAST:event_btSaveMouseReleased
    
    private boolean isDataValid(){
        boolean flag = false;
        if(frmTxtCols.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Cannot be empty","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtCols.requestFocus();
        }
        else if(Integer.parseInt(frmTxtCols.getText().trim())==0){
            JOptionPane.showMessageDialog(this,"Cannot be zero","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtCols.requestFocus();            
        }
        else if(frmTxtLines.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Cannot be empty","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtLines.requestFocus();
        }
        else if(Integer.parseInt(frmTxtLines.getText().trim())==0){
            JOptionPane.showMessageDialog(this,"Cannot be zero","",JOptionPane.INFORMATION_MESSAGE);
            frmTxtLines.requestFocus();            
        }        
        else
            flag=true;
        return flag;
    }
    
    private void btSavePressed(){
        if(isDataValid())
            if(cnt.updatePageSettings(new Object[]{frmTxtCols.getText().trim(),frmTxtLines.getText().trim()})){
                JOptionPane.showMessageDialog(this,"Data modified successfully","Saved:",JOptionPane.INFORMATION_MESSAGE);
                //clearInputs();
            }
            else
                JOptionPane.showMessageDialog(this,"Data could not be modified","Sorry:",JOptionPane.ERROR_MESSAGE);
    }
    
    private void clearInputs(){
        frmTxtCols.setText("");
        frmTxtLines.setText("");
    }
    
    private void btClosePressed(){
        this.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btSave;
    private javax.swing.JFormattedTextField frmTxtCols;
    private javax.swing.JFormattedTextField frmTxtLines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
    
    private SettingsController cnt = new SettingsController();
}
