/*
 * MonthRollPageSettingsView.java
 *
 * Created on 11 May 2004, 20:25
 */

package view;

/**
 *
 * @author  paawak
 */
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

import controller.SettingsController;

public class MonthRollTDSTaxSettingsView extends javax.swing.JPanel {

    private static final long serialVersionUID = -107136687419055492L;

    /** Creates new form MonthRollPageSettingsView */
    public MonthRollTDSTaxSettingsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        pnlTitle = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        frmTxtTDSPercent = new javax.swing.JFormattedTextField(
                new java.text.DecimalFormat("0.00"));
        jLabel2 = new javax.swing.JLabel();
        frmTxtTDSApplyAmt = new javax.swing.JFormattedTextField(
                new java.text.DecimalFormat("0.00"));
        btSave = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        frmTxtTaxPercent = new javax.swing.JFormattedTextField(
                new java.text.DecimalFormat("0.00"));

        lbFuelCharges = new javax.swing.JLabel();
        frmTxtFuelCharges = new javax.swing.JFormattedTextField(
                new java.text.DecimalFormat("0.00"));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitle.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17
                .setText("<html><u>TDS/Tax Settings For Invoice File</u></html>");
        pnlTitle.add(jLabel17, java.awt.BorderLayout.CENTER);

        add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330,
                30, 440, 30));

        jLabel1.setText("TDS Percent :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300,
                150, -1, -1));

        frmTxtTDSPercent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtTDSPercent.setText(cnt.getTDSPercent());
        frmTxtTDSPercent
                .setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);
        add(frmTxtTDSPercent,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150,
                        140, -1));

        jLabel2.setText("TDS Cut-off Amount :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300,
                190, -1, -1));

        frmTxtTDSApplyAmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtTDSApplyAmt.setText(cnt.getTDSApplyAmt());
        frmTxtTDSApplyAmt
                .setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);
        add(frmTxtTDSApplyAmt,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190,
                        140, -1));

        btSave.setMnemonic('s');
        btSave.setText("Save");
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveMouseReleased(evt);
            }
        });

        add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310,
                -1, -1));

        btClose.setMnemonic('c');
        btClose.setText("Close");
        btClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCloseMouseReleased(evt);
            }
        });

        add(btClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560,
                310, -1, -1));

        jLabel3.setText("Tax Percent :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300,
                230, -1, -1));

        frmTxtTaxPercent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtTaxPercent.setText(cnt.getTaxPercent());
        frmTxtTaxPercent
                .setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);
        add(frmTxtTaxPercent,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230,
                        140, -1));

        lbFuelCharges.setText("Fuel Charge :");
        add(lbFuelCharges, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                300, 270, -1, -1));

        frmTxtFuelCharges.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frmTxtFuelCharges.setText(cnt.getFuelCharge());
        frmTxtFuelCharges
                .setFocusLostBehavior(JFormattedTextField.COMMIT_OR_REVERT);
        add(frmTxtFuelCharges,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270,
                        140, -1));

    }// GEN-END:initComponents

    private void btCloseMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btCloseMouseReleased
        // Add your handling code here:
        btClosePressed();
    }// GEN-LAST:event_btCloseMouseReleased

    private void btSaveMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btSaveMouseReleased
        // Add your handling code here:
        btSavePressed();
    }// GEN-LAST:event_btSaveMouseReleased

    private boolean isDataValid() {
        boolean flag = false;
        if (frmTxtTDSPercent.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Cannot be empty", "",
                    JOptionPane.INFORMATION_MESSAGE);
            frmTxtTDSPercent.requestFocus();
        } else if (frmTxtTDSApplyAmt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Cannot be empty", "",
                    JOptionPane.INFORMATION_MESSAGE);
            frmTxtTDSApplyAmt.requestFocus();
        } else if (Float.parseFloat(frmTxtTDSApplyAmt.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "Cannot be zero", "",
                    JOptionPane.INFORMATION_MESSAGE);
            frmTxtTDSApplyAmt.requestFocus();
        } else if (frmTxtTaxPercent.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Cannot be empty", "",
                    JOptionPane.INFORMATION_MESSAGE);
            frmTxtTaxPercent.requestFocus();
        } else if (frmTxtFuelCharges.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Cannot be empty", "",
                    JOptionPane.INFORMATION_MESSAGE);
            frmTxtFuelCharges.requestFocus();
        } else
            flag = true;
        return flag;
    }

    private void btSavePressed() {
        if (isDataValid())
            try {
                if (cnt.updateTDSTaxSettings(new Object[] {
                        frmTxtTDSPercent.getText().trim(),
                        frmTxtTDSApplyAmt.getText().trim(),
                        frmTxtTaxPercent.getText().trim() })
                        && cnt.insertOrUpdateFuelCharges(frmTxtFuelCharges
                                .getText().trim())) {
                    JOptionPane.showMessageDialog(this,
                            "Data modified successfully", "Saved:",
                            JOptionPane.INFORMATION_MESSAGE);
                    // clearInputs();
                } else
                    JOptionPane.showMessageDialog(this,
                            "Data could not be modified", "Sorry:",
                            JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }

    // private void clearInputs() {
    // frmTxtTDSPercent.setText("");
    // frmTxtTDSApplyAmt.setText("");
    // frmTxtTaxPercent.setText("");
    // }

    private void btClosePressed() {
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btSave;
    private javax.swing.JFormattedTextField frmTxtTDSApplyAmt;
    private javax.swing.JFormattedTextField frmTxtTDSPercent;
    private javax.swing.JFormattedTextField frmTxtTaxPercent;
    private javax.swing.JFormattedTextField frmTxtFuelCharges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbFuelCharges;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables

    private SettingsController cnt = new SettingsController();
}
